/*
CHAR
10BYTE
*/

CREATE TABLE TB_CHAR(
  컬럼1 CHAR(10 BYTE), 
  컬럼2 CHAR(10 CHAR),
  컬럼3 CHAR(10)
);

INSERT INTO TB_CHAR("컬럼1", "컬럼2", "컬럼3")
VALUES('ABC', 'ABC', 'ABC');

INSERT INTO TB_CHAR("컬럼1", "컬럼2", "컬럼3")
VALUES('가나다', '가나다', '가나다');
  --한글 == 3 BYTE 3 + 9
SELECT * FROM TB_CHAR;

SELECT "컬럼1", 컬럼2, 컬럼3,
  LENGTHB(컬럼1), LENGTHB(컬럼2), LENGTHB(컬럼3)
  FROM TB_CHAR;
  
  -- VARCHAR, VARCHAR2
  
  CREATE TABLE TB_VARCHAR(
  COL1 VARCHAR2(10 BYTE),
  COL2 VARCHAR2(10 CHAR),
  COL3 VARCHAR2(10)
  );
  
  INSERT INTO TB_VARCHAR(COL1, COL2, COL3)
  VALUES('ABC', 'ABC', 'ABC');
  
  INSERT INTO TB_VARCHAR(COL1, COL2, COL3)
  VALUES('가나다', '가나다', '가나다');

  SELECT * FROM TB_VARCHAR;
  
  SELECT COL1, COL2, COL3, LENGTHB(COL1), LENGTHB(COL1), LENGTHB(COL1)
  FROM TB_VARCHAR;
  
  /*
  NCHAR, NVARCHAR2 거의 사용하지 않는다.
  다국어 저장을 위해 생겼다.
  사용법은 동일!
  */
  
  CREATE TABLE TB_NCHAR(
    COL1 NCHAR(10),
    COL2 NVARCHAR2(10)
  );
  
  INSERT INTO TB_NCHAR(COL1, COL2)
  VALUES('ABCD', 'ABCD');
  
  SELECT LENGTHB (COL1) , LENGTHB (COL2)
    FROM TB_NCHAR;
    
  CREATE TABLE TB_LONG(
    COL1 LONG
    --COL2 LONG
  );
  
  INSERT INTO TB_LONG(COL1)
  VALUES('SDFSFDSFSDFSF');
  
  -- LONG 형태는 너무길어서 한테이블에 하나만 사용해야 한다!
  
  /*
  숫자 자료형
  NUMBER
  NUMBER(5)
  NUMBER(5,2) 최대 정수 자리 3자리 소수 2자리
  NUMBER(*, 2)  
  */
  
  CREATE TABLE TB_NUMBER(
    COL1 NUMBER,
    COL2 NUMBER(5),
    COL3 NUMBER(5,2),
    COL4 NUMBER(*,2)
  );
  
  INSERT INTO TB_NUMBER(COL1, COL2, COL3, COL4)
  VALUES(1234.56789, 1234.56789, 124.896, 1234.56789);
  
  SELECT * FROM TB_NUMBER;
  
  -- DATE
  
  CREATE TABLE TB_DATE(
    COL1 DATE,
    COL2 DATE
  );
  --SYSDATE : 현재의 시간까지 구할 수 있다.
  INSERT INTO TB_DATE(COL1, COL2)
  VALUES(SYSDATE -1, TO_DATE('2016-12-25 12:30:23', 'YYYY-MM-DD HH24:MI:SS'));
  
  SELECT * FROM TB_DATE;
  
   INSERT INTO TB_DATE(COL1, COL2)
  VALUES(SYSDATE -1, ADD_MONTHS(SYSDATE, -1));
  
  