
SELECT CHR(48) FROM DUAL;

-- CHR(97) ASCII 문자로 변환하는 함수
-- DUAL : 더미 테이블 (간단한 값을 알아볼 수 있는 임시 테이블)

--LPAD : 문자열로 채워준다

SELECT LPAD('BBB', 10) FROM DUAL; 

SELECT LPAD('BBB', 10, '-') FROM DUAL; 

SELECT RPAD('BBB', 10, '-') FROM DUAL; 

--INSTR

SELECT INSTR('A12345BA6789C', 'A', 2) FROM DUAL;

SELECT INSTR('BA12345BBA6789C', 'B', 3) FROM DUAL;

SELECT REPLACE('AAAAAAAVVVVVVVFFFFEEDSS', 'A', 'B')
FROM DUAL;

--REPLACE(여러 문자) TRANSLATE(한 문자)
SELECT TRANSLATE('AAAAAAAAAVVFDFD', 'AA', 'C')
FROM DUAL;

SELECT REPLACE('AAAAAAAAAVVFDFD', 'AA', 'C')
FROM DUAL;

--반올림
SELECT CEIL(13.2) FROM DUAL;

-- 내림
SELECT FLOOR(-13.5) FROM DUAL;

-- 나머지
SELECT MOD(3,2) FROM DUAL;

-- POW
SELECT POWER(2, 3) FROM DUAL;

--반올림
SELECT ROUND(13.4) FROM DUAL;

--부호
SELECT SIGN(0) FROM DUAL; -- 양수 : 1, 음수 : -1, 0 : 0

--버림

SELECT TRUNC(13.4543543, -2) FROM DUAL;

SELECT ASCII('A') FROM DUAL;

-- TO_CHAR
SELECT TO_CHAR(SYSDATE)
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS')
FROM DUAL;

SELECT TO_CHAR(10000)
FROM DUAL;

SELECT TO_CHAR(10000, '999,999')
FROM DUAL;

SELECT TO_DATE('20161206')
FROM DUAL;

SELECT to_number('123')
FROM DUAL;

-- ADD_MONTHS : 날짜에 N만큼 더한 날짜
SELECT SYSDATE, ADD_MONTHS(SYSDATE, 1)
FROM DUAL;

SELECT LAST_DAY(SYSDATE)
FROM DUAL;


SELECT LAST_DAY(TO_DATE('2016-10-11', 'YYYY-MM-DD'))
FROM DUAL;

SELECT LOWER('ABc') FROM DUAL;

SELECT UPPER('AVc') FROM DUAL;











