
SELECT DEPARTMENT_ID
FROM EMPLOYEES;

DESC EMPLOYEES;

DESC JOBS;

SELECT EMPLOYEES.EMPLOYEE_ID
FROM EMPLOYEES;

SELECT FIRST_NAME AS 이름, LAST_NAME AS 성 
FROM EMPLOYEES
WHERE FIRST_NAME = 'Alexander';

SELECT '이름:', 20, FIRST_NAME, LAST_NAME
FROM EMPLOYEES;

--연봉
SELECT FIRST_NAMEE, LAST_NAME, SALARY * 12 As 연봉
FROM EMPLOYEES;

SELECT '이름:'|| LAST_NAME || ' ' || FIRST_NAME
FROM EMPLOYEES;

SELECT * FROM EMPLOYEES;

SELECT DESC
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, JOB_ID
FROM EMPLOYEES;

SELECT FIRST_NAME, SALARY, SALARY+300
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, commission_pct*salary, SALARY+ commission_pct*salary
FROM EMPLOYEES;

SELECT LAST_NAME AS Name, SALARY*12 AS "Annual Salary"
FROM EMPLOYEES;

SELECT LAST_NAME || ' ' || JOB_ID AS Employees
FROM EMPLOYEES;

SELECT LAST_NAME || ' is a ' || JOB_ID AS "Employees Details"
FROM EMPLOYEES;

SELECT LAST_NAME || ': 1 Year salary = ' || SALARY AS "MONTHLY"
FROM EMPLOYEES;





