/*
  VIEW : WINDOW
  TABLE(저장) VS VIEW(가상테이블)
  가독성
  뷰를 통해서 데이터를 관리할 수 있다, 한개의 뷰로 여러개의 테이블 검색
*/

CREATE OR REPLACE VIEW UV_TEST_01(
  JOB_ID,
  JOB_TITLE,
  MIN_SALARY
)AS
SELECT JOB_ID, JOB_TITLE, MIN_SALARY FROM JOBS;

CREATE OR REPLACE VIEW UV_TEST_02
AS SELECT * FROM UV_TEST_01;

DROP VIEW UV_TEST_01;
DROP VIEW UV_TEST_02;

SELECT * FROM UV_TEST_02;

CREATE TABLE TB_TEST_03(
  KEY_01 VARCHAR2(10),
  KEY_02 VARCHAR2(10),
  COL_01 VARCHAR2(100),
  COL_02 VARCHAR2(100),
  CONSTRAINT PK_TEST_04 PRIMARY KEY(KEY_01,KEY_02)
);

DROP TABLE UV_TEST_03;

SELECT * FROM UV_TEST_03;

CREATE OR REPLACE VIEW UV_TEST_03(
  KEY_01,
  KEY_02,
  COL_01,
  CONSTRAINT PK_UV_TEST_03 PRIMARY KEY(KEY_01) DISABLE NOVALIDATE
)
AS SELECT KEY_01, KEY_02, COL_01
FROM TB_TEST_03;

INSERT INTO UV_TEST_03(KEY_01, KEY_02, COL_01)
VALUES('AAA','AAA','AAA');

SELECT * FROM UV_TEST_03;
SELECT * FROM TB_TEST_03;

UPDATE UV_TEST_03 SET COL_01 = 'BBB'
WHERE KEY_01 = 'AAA' AND KEY_02 = 'AAA';

DROP VIEW UV_TEST_03;

CREATE OR REPLACE VIEW UV_TEST_04
AS SELECT KEY_01,KEY_02,COL_01
FROM TB_TEST_03
WITH READ ONLY; --INSERT 안됌
