/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2017-02-21 05:15:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.Beans.Ya_ReviewBean;
import com.Dao.ReviewDao;
import java.util.Date;
import java.util.Locale;
import java.text.SimpleDateFormat;
import com.Beans.Ya_MemberBean;
import com.Beans.Ya_MotelBean;
import com.Dao.MemberDao;
import com.Beans.Ya_ZzimBean;
import com.Dao.ZzimDao;
import com.Dao.ReserveDao;
import com.Beans.Ya_ReserveBean;
import java.util.ArrayList;
import com.Dao.PointDao;

public final class mypage_005fControl_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.Beans.Ya_MotelBean");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("com.Dao.PointDao");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("com.Dao.ZzimDao");
    _jspx_imports_classes.add("com.Beans.Ya_MemberBean");
    _jspx_imports_classes.add("com.Dao.MemberDao");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.Beans.Ya_ReserveBean");
    _jspx_imports_classes.add("com.Dao.ReviewDao");
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("com.Beans.Ya_ReviewBean");
    _jspx_imports_classes.add("com.Beans.Ya_ZzimBean");
    _jspx_imports_classes.add("com.Dao.ReserveDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("UTF-8");

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

	String command = request.getParameter("command");
	String value = request.getParameter("value");
	Ya_MemberBean memberBean = (Ya_MemberBean)session.getAttribute("member");
	  
	if(command.equals("guestzzimlist")){
		String email = request.getParameter("email");
		int pageSize = 6;
		System.out.println(value);
		
		if(value.equals("init")){
			int pageNum = 1;
			ZzimDao zzimDao = ZzimDao.getInstance();
			ArrayList<Ya_ZzimBean> list = zzimDao.do_getzzimlist(pageNum, pageSize, "", email);
			System.out.println("사이즈를 알아보자! : " + list.size());
			System.out.println("사이즈를 알아보자! : " + email);
			request.setAttribute("zzimlist", list);
		}else if(value.equals("after")){
			int pageNum = Integer.parseInt(request.getParameter("pageNum"));
			ZzimDao zzimDao = ZzimDao.getInstance();
			ArrayList<Ya_ZzimBean> list = new ArrayList<Ya_ZzimBean>();
			list = zzimDao.do_getzzimlist(pageNum, pageSize, "", email);
			request.setAttribute("zzimlist", list);			
		}
		pageContext.forward("mypage_Main.jsp?contentsDiv=guestzzimlist");
	
	}else if(command.equals("hostreviewlist")){
		int motelNum = memberBean.getMotel_num();
		String page_size = "1";	//페이지 사이즈 변경!!
		int pageSize = Integer.parseInt(page_size);
		System.out.println(value);
		
		if(value.equals("init")){
			int pageNum = 1;
			ReviewDao reviewDao = ReviewDao.getInstance();
			ArrayList<Ya_ReviewBean> list = reviewDao.do_search(pageNum, pageSize, motelNum);
			System.out.println("사이즈를 알아보자! : " + list.size());
			request.setAttribute("reviewlist", list);
			request.setAttribute("pageSize", pageSize);
		}else if(value.equals("after")){
			int pageNum = request.getParameter("pageNum") == "" || request.getParameter("pageNum") == null ? 1 : Integer.parseInt(request.getParameter("pageNum"));
			ReviewDao reviewDao = ReviewDao.getInstance();
			ArrayList<Ya_ReviewBean> list = reviewDao.do_search(pageNum, pageSize, motelNum);
			System.out.println("사이즈를 알아보자! : " + list.size());
			request.setAttribute("reviewlist", list);
			request.setAttribute("pageSize", pageSize);
		}
		pageContext.forward("mypage_Main.jsp?contentsDiv=hostreviewlist");
	}else if(command.equals("guestpointlist")){
		
		String email = request.getParameter("email");
		int pageSize = 5;
		
		if(value.equals("init")){
			int pageNum = 1;
			PointDao pdao = PointDao.getInstance();
			ArrayList<Ya_ReserveBean> bean_list = new ArrayList<Ya_ReserveBean>();
			bean_list = pdao.do_getpointlist(pageNum, pageSize, email);
			request.setAttribute("bean_list", bean_list);
		}else if(value.equals("after")){
			int pageNum = Integer.parseInt(request.getParameter("pageNum"));
			PointDao pdao = PointDao.getInstance();
			ArrayList<Ya_ReserveBean> bean_list = new ArrayList<Ya_ReserveBean>();
			bean_list = pdao.do_getpointlist(pageNum, pageSize, email);
			request.setAttribute("bean_list", bean_list);
		}
		pageContext.forward("mypage_Main.jsp?contentsDiv=guestpointlist");
	}else if(command.equals("guestreservelist")){
		pageContext.forward("mypage_Main.jsp?contentsDiv=guestreservelist");
	}else if(command.equals("guestmemupdate")){
		pageContext.forward("mypage_Main.jsp?contentsDiv=guestmemupdate");
	}else if(command.equals("hostmotelupdate")){
		pageContext.forward("mypage_Main.jsp?contentsDiv=hostmotelupdate");
	}else if(command.equals("hostreservelist")){
		String email = request.getParameter("email");
		int pageSize = 5;
		int m_num = memberBean.getMotel_num();
		if(value.equals("init")){
			SimpleDateFormat formatter = new SimpleDateFormat ( "yyyy/MM/dd", Locale.KOREA );
			Date currentTime = new Date();
			Date yestTime = new Date();
			yestTime.setTime(new Date().getTime() - (1 * 24 * 60 * 60 * 1000));

			String dTime = formatter.format ( currentTime );
			String yTime = formatter.format ( yestTime );
			
			int pageNum = 1;
			ReserveDao reserveDao = ReserveDao.getInstance();
			ArrayList<Ya_ReserveBean> reservelist = new ArrayList<Ya_ReserveBean>();
			reservelist = reserveDao.do_host_getlist(pageNum, pageSize, m_num, yTime, dTime);
			System.out.println("예약내역 : " + reservelist.size());
			request.setAttribute("reservelist", reservelist);
		}else if(value.equals("after")){
			int pageNum = Integer.parseInt(request.getParameter("pageNum"));
			String date1 = request.getParameter("date1");
			String date2 = request.getParameter("date2");
			ReserveDao reserveDao = ReserveDao.getInstance();
			ArrayList<Ya_ReserveBean> reservelist = new ArrayList<Ya_ReserveBean>();
			reservelist = reserveDao.do_host_getlist(pageNum, pageSize, m_num, date1, date2);
			request.setAttribute("reservelist", reservelist);
		}
		pageContext.forward("mypage_Main.jsp?contentsDiv=hostreservelist");
	}else if(command.equals("hostreviewlist")){
		pageContext.forward("mypage_Main.jsp?contentsDiv=hostreviewlist");
	}else if(command.equals("adminAdmission")){
		MemberDao dao = MemberDao.getInstance();
		
		String pageNumStr = (request.getParameter("pageNum")==null||request.getParameter("pageNum")=="")?"1":request.getParameter("pageNum");
		String search_div = (request.getParameter("search_div")==null||request.getParameter("search_div")=="")?"":request.getParameter("search_div");
		String search_word =(request.getParameter("search_word")==null||request.getParameter("search_word")=="")?"":request.getParameter("search_word");
		
		
		int pageNum = Integer.parseInt(pageNumStr);
		String pageSize = "1";	//페이지 사이즈 변경!!
		int page_Size = Integer.parseInt(pageSize);
		
		System.out.println(search_div);
		System.out.println(search_word);
		System.out.println(pageNum);
		
		ArrayList<Object> list = dao.do_search_notIsOk(pageNum, page_Size, search_div, search_word);
		
		if(list.size()==0){
			
			System.out.println("걸린거임 ");
			pageContext.forward("mypage_Main.jsp?contentsDiv=adminAdmission");
			
		}else{
			request.setAttribute("list", list);
			request.setAttribute("pageNum", pageNumStr);
			request.setAttribute("pageSize", pageSize);
			request.setAttribute("search_div", search_div);
			request.setAttribute("search_word", search_word);
			
			pageContext.forward("mypage_Main.jsp?contentsDiv=adminAdmission");
		}
	}else if(command.equals("detail")){
		MemberDao dao = MemberDao.getInstance();
		
		String email = request.getParameter("email");
		
		int seq = dao.search_motelNum(email);
		
		//System.out.println("중요포인트ㅡ으으으으 : " + email);
		
		Ya_MotelBean motel = (Ya_MotelBean)dao.do_detail(seq);
		
		request.setAttribute("motel", motel);
		
		pageContext.forward("mypage_Main.jsp?contentsDiv=detail");
	}else if(command.equals("access")){
		MemberDao dao = MemberDao.getInstance();
		String m = request.getParameter("email");
		System.out.println("들어온 이메일 : " + m);
		
		if(dao.do_admin_access(m)){
			System.out.println("승인성공!!");
			pageContext.forward("mypage_Control.jsp?command=adminAdmission");
		}
	}else if(command.equals("reviewAnswer")){
		int seq = Integer.parseInt(request.getParameter("seq"));
		int motel_num = Integer.parseInt(request.getParameter("motel_num"));
		String nickname = request.getParameter("nickname");
		String reply = request.getParameter("reply");
		int clean = Integer.parseInt(request.getParameter("clean"));
		int facility = Integer.parseInt(request.getParameter("facility"));
		int service = Integer.parseInt(request.getParameter("service"));
		
		System.out.println("씨이큐~~~ : " + seq);
		System.out.println("모텔넘~~~ : " + motel_num);
		System.out.println("닉네엠~~~ : " + nickname);
		System.out.println("컨텐츠~~~ : " + reply);
		System.out.println("청결점수~ : " + clean);
		System.out.println("시설점수~~~ : " + facility);
		System.out.println("서비스점수~~~ : " + service);
		
		
		Ya_ReviewBean bean = new Ya_ReviewBean();
		bean.setSeq(seq);
		bean.setMotel_num(motel_num);
		bean.setNickname(nickname);
		bean.setContent(reply);
		bean.setClean(clean);
		bean.setFacility(facility);
		bean.setService(service);
		
		ReviewDao dao = ReviewDao.getInstance();
		
		dao.do_upsert(bean);
		
		pageContext.forward("mypage_Control.jsp?command=hostreviewlist&value=after");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
