/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2017-02-20 06:50:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.Beans.Ya_ReviewBean;
import java.util.HashMap;
import com.Beans.Ya_ZzimBean;
import com.Dao.ZzimDao;
import java.util.ArrayList;
import com.Beans.Ya_MemberBean;
import com.Dao.MyPageDao;

public final class mypage_005fMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.Beans.Ya_ReviewBean");
    _jspx_imports_classes.add("com.Dao.MyPageDao");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("com.Dao.ZzimDao");
    _jspx_imports_classes.add("com.Beans.Ya_ZzimBean");
    _jspx_imports_classes.add("com.Beans.Ya_MemberBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
	
	String email = "";
	int auth = 0; 
	
	Ya_MemberBean memberBean = (Ya_MemberBean)session.getAttribute("member");
	email = memberBean.getEmail();
	auth = memberBean.getAuth();
	
	MyPageDao mpdao = MyPageDao.getInstance();
	HashMap<String,Integer> map = new HashMap<String,Integer>();
	map = mpdao.do_count_member_state(email);

	String contents = "";
	String contentsDiv = request.getParameter("contentsDiv");
	System.out.println(contentsDiv);
	if(contentsDiv==null) contents = "mypage_Control.jsp?command=guestzzimlist&value=init&email="+email;
	else if(contentsDiv.equals("guestzzimlist")){
		contents = "../mypage/ya_Guest_Zzim.jsp";
		ArrayList<Ya_ZzimBean> list = new ArrayList<Ya_ZzimBean>();
		list = (ArrayList<Ya_ZzimBean>)request.getAttribute("zzimlist");
		request.setAttribute("zzimlist", list);		
	}
	else if(contentsDiv.equals("guestpointlist")) contents = "../mypage/ya_Guest_Point.jsp";
	else if(contentsDiv.equals("guestreservelist")) contents = "../mypage/ya_Guest_Reserve.jsp";
	else if(contentsDiv.equals("guestmemupdate")) contents = "../mypage/ya_Guest_MemUpdate.jsp";
	else if(contentsDiv.equals("hostmotelupdate")) contents = "../mypage/ya_Host_MotelUpdate.jsp";
	else if(contentsDiv.equals("hostreservelist")) contents = "../mypage/ya_Host_Reserve.jsp";
	else if(contentsDiv.equals("hostreviewlist")){
		contents = "../mypage/ya_Host_Review.jsp";
		ArrayList<Ya_ReviewBean> list = new ArrayList<Ya_ReviewBean>();
		list = (ArrayList<Ya_ReviewBean>)request.getAttribute("reviewlist");
		request.setAttribute("reviewlist", list);
	}
	else if(contentsDiv.equals("adminAdmission")) {
		ArrayList<Object> list = (ArrayList<Object>)request.getAttribute("list");
		String pageNum = request.getParameter("pageNum");
		String pageSize = request.getParameter("pageSize");
		String search_div = request.getParameter("search_div");
		String search_word = request.getParameter("search_word");
		
		request.setAttribute("list", list);
		request.setAttribute("pageNum", pageNum);
		request.setAttribute("pageSize", pageSize);
		request.setAttribute("search_div", search_div);
		request.setAttribute("search_word", search_word);
		contents = "../mypage/ya_Admin_Admission.jsp";
	}else if(contentsDiv.equals("detail")) contents = "../mypage/ya_Admin_Detail.jsp";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://openapi.map.naver.com/openapi/v2/maps.js?clientId=xAmZfYgSTz_6UArTCRhz\"></script>\r\n");
      out.write("<!-- prevent IE6 flickering -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    try {\r\n");
      out.write("        document.execCommand('BackgroundImageCache', false, true);\r\n");
      out.write("    } catch (e) {\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<title>MyPage</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.header{\r\n");
      out.write("\t\tposition : fixed;\r\n");
      out.write("\t\theight : 100px;\r\n");
      out.write("\t\tbackground: #fc676e;\r\n");
      out.write("\t\tz-index: 10;\r\n");
      out.write("\t}\r\n");
      out.write("\t.foot{\r\n");
      out.write("\t\theight : 200px;\r\n");
      out.write("\t\tbackground: #3f3e3e;\r\n");
      out.write("\t}\r\n");
      out.write("\t.blank{\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t.location{\r\n");
      out.write("\t\tpadding-top : 50px;\r\n");
      out.write("\t\theight: 300px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.popular{\r\n");
      out.write("\t\theight: 300px;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable,tr,td{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Top -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../super/superTop.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- 빈곳   -->\t\r\n");
      out.write("\t<div class=\"blank\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    \t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    \t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td></td>\r\n");
      out.write("    \t\t<td colspan=\"7\">________</td>\r\n");
      out.write("    \t\t<td></td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- mypageMain -->\t\r\n");
      out.write("\t<div class=\"mypage\" >\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<table width=\"1300\" height=\"900\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t<!-- Left -->\r\n");
      out.write("\t\t\t<td rowspan=\"2\" width=\"300\" height=\"900\" valign=\"top\">\r\n");
      out.write("\t\t<!-- menu -->\r\n");
      out.write("\t\t\t\t<div style=\"padding: 30px\">\r\n");
      out.write("\t\t\t\t<p><h1>마이페이지</h1></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t<!-- //menu -->\r\n");
      out.write("\t\t\t\t<p><hr></p>\r\n");
      out.write("\t\t<!-- guest_menu -->\t\t\t\r\n");
      out.write("\t\t\t\t<div name=\"guest_menu\" align=\"left\" style=\"padding-left: 50px\">\r\n");
      out.write("\t\t\t\t<p style=\"padding: 5px\">\r\n");
      out.write("\t\t\t\t\t<a href=\"mypage_Control.jsp?command=guestzzimlist&email=");
      out.print(email);
      out.write("&value=init\"><h2>찜</h2></a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p style=\"padding: 5px\">\r\n");
      out.write("\t\t\t\t\t<a href=\"mypage_Control.jsp?command=guestpointlist&email=");
      out.print(email);
      out.write("&value=init\"><h2>포인트</h2></a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p style=\"padding: 5px\">\r\n");
      out.write("\t\t\t\t\t<a href=\"mypage_Control.jsp?command=guestreservelist\"><h2>예약내역</h2></a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p style=\"padding: 5px\">\r\n");
      out.write("\t\t\t\t\t<a href=\"../mypage/mypage_Control.jsp?command=guestmemupdate\"><h2>회원정보수정</h2></a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");

	            if(auth==2){
	            
      out.write("\r\n");
      out.write("\t            <div name=\"admin_menu\" align=\"left\" style=\"padding-left: 50px\">\r\n");
      out.write("\t            <p style=\"padding: 5px\">\r\n");
      out.write("\t               <a href=\"mypage_Control.jsp?command=adminAdmission\"><h2>회원 승인하기</h2></a>\r\n");
      out.write("\t            </p>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            ");

	            }
	            
      out.write("\r\n");
      out.write("\t\t\t\t");

				if(auth==1){
				
      out.write("\r\n");
      out.write("\t\t<!-- //guest_menu -->\r\n");
      out.write("\t\t\t\t<p><hr></p>\r\n");
      out.write("\t\t<!-- host_menu -->\t\t\t\r\n");
      out.write("\t\t\t\t<div name=\"host_menu\" align=\"left\" style=\"padding-left: 50px\">\r\n");
      out.write("\t\t\t\t<p style=\"padding: 5px\">\r\n");
      out.write("\t\t\t\t\t<a href=\"mypage_Control.jsp?command=hostmotelupdate\"><h2>모텔정보수정</h2></a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p style=\"padding: 5px\">\r\n");
      out.write("\t\t\t\t\t<a href=\"mypage_Control.jsp?command=hostreservelist&value=init\"><h2>예약확인</h2></a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<p style=\"padding: 5px\">\r\n");
      out.write("\t\t\t\t\t<a href=\"mypage_Control.jsp?command=hostreviewlist&value=init\"><h2>리뷰관리</h2></a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");

				}
				
      out.write("\r\n");
      out.write("\t\t<!-- //host_menu -->\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t<!-- //Left -->\r\n");
      out.write("\t<!-- Top -->\r\n");
      out.write("\t\t\t<td width=\"1000\" height=\"120\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"250\" height=\"150\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"\" src=\"../img/couple.png\" width=\"100\" height=\"100\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"250\" height=\"150\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3><img alt=\"\" src=\"../img/love.png\" width=\"80\" height=\"80\"></h3><br>\r\n");
      out.write("\t\t\t\t\t\t\t<p name=\"zzim_count\">");
      out.print(map.get("zzim")==null?0:map.get("zzim") );
      out.write("개 </p>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"250\" height=\"150\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3><img alt=\"\" src=\"../img/point.png\" width=\"80\" height=\"80\"></h3><br>\r\n");
      out.write("\t\t\t\t\t\t\t<p name=\"point_sum\">");
      out.print(map.get("point")==null?0:map.get("point") );
      out.write("원 </p>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"250\" height=\"150\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3><img alt=\"\" src=\"../img/list.png\" width=\"80\" height=\"80\"></h3><br>\r\n");
      out.write("\t\t\t\t\t\t\t<p name=\"reserve_count\">");
      out.print(map.get("reserve")==null?0:map.get("reserve") );
      out.write("개 </p>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t<!-- //Top -->\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t<!-- Contents -->\r\n");
      out.write("\t\t\t<td width=\"1000\" height=\"750\" valign=\"top\" style=\"padding-top: 50px\" bgcolor=\"#f3f3f3\">\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, contents , out, false);
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t<!-- //Contents -->\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!--Foot -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../super/superFoot.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
