/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2017-02-21 05:22:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.Beans.Ya_ReserveBean;
import java.util.ArrayList;
import java.util.Calendar;

public final class ya_005fHost_005fReserve_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.Beans.Ya_ReserveBean");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");

Calendar cal = Calendar.getInstance();
int tyear = cal.get(Calendar.YEAR);
int tmonth = cal.get(Calendar.MONTH)+1;
int tday = cal.get(Calendar.DATE);
String todaydate = "";

if(tmonth<10){
	if(tday<10){
		todaydate = tyear+"-0"+tmonth+"-0"+tday;
	}else{
		todaydate = tyear+"-0"+tmonth+"-"+tday;
	}
}else{
	if(tday<10){
		todaydate = tyear+"-"+tmonth+"-0"+tday;
	}else{
		todaydate = tyear+"-"+tmonth+"-"+tday;
	}
}
System.out.println(todaydate);
ArrayList<Ya_ReserveBean> reservelist = new ArrayList<Ya_ReserveBean>();
reservelist = (ArrayList<Ya_ReserveBean>)request.getAttribute("reservelist");

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function choice(choicevalue,seqNum,point,price){\r\n");
      out.write("\tif(choicevalue==0){\r\n");
      out.write("\t\t// 확인으로 변경\r\n");
      out.write("\t\tvar seq = seqNum;\r\n");
      out.write("\t\talert(\"예약확인으로!\"+seq);\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\turl:\"../mypage/ya_Host_Reserve_Admission.jsp\",\r\n");
      out.write("\t\t\tdataType:\"html\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\"seq\":\tseq,\r\n");
      out.write("\t\t\t\t\"point\": point,\r\n");
      out.write("\t\t\t\t\"price\": price\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tconsole.log(\"success\\t\"+data);\r\n");
      out.write("\t\t\t\tvar flag1 = $.parseJSON(data);\r\n");
      out.write("\t\t\t\tvar flag2 = $.parseJSON(data);\r\n");
      out.write("\t\t\t\t//var pay_dt = flag.pay_dt;\r\n");
      out.write("\t\t\t\tif(!flag1){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"해당회원의 상태가 갱신되어 승인이 취소되었습니다.\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tconsole.log(\"complete=\"+flag1 + flag2);\r\n");
      out.write("\t\t\t\tpage(1);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcomplete : function(data) {\r\n");
      out.write("\t\t        // 통신이 실패했어도 완료가 되었을 때 이 함수를 타게 된다.\r\n");
      out.write("\t        \tconsole.log(\"complete\"+data);\r\n");
      out.write("\t        },           \r\n");
      out.write("\t        error:function(){\r\n");
      out.write("\t        }\r\n");
      out.write("\t\t});\t \r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function page(page){\r\n");
      out.write("\tvar date1 = $('#date1').val();\r\n");
      out.write("\tvar date2 = $('#date2').val();\r\n");
      out.write("\tvar pageNum = page;\r\n");
      out.write("\t//console.log(date1);\r\n");
      out.write("\t//console.log(date2);\r\n");
      out.write("    \r\n");
      out.write("\t$.ajax({\r\n");
      out.write("        type:\"POST\",\r\n");
      out.write("        url:\"ya_Host_Reserve_Check.jsp\",\r\n");
      out.write("        dataType:\"html\",\r\n");
      out.write("        data:{\r\n");
      out.write("            \"date1\":  date1,\r\n");
      out.write("            \"date2\":  date2,\r\n");
      out.write("            \"pageNum\" : pageNum\r\n");
      out.write("        },\r\n");
      out.write("        success:function(data){\r\n");
      out.write("        \t//console.log(\"success\\t\"+data);\t\t\t\t\t\t// 데이터 잘 받는지 확인(결과 리스트를 배열처럼 받음)\r\n");
      out.write("        \tvar beanData = $.parseJSON(data);\r\n");
      out.write("        \t//console.log(\"complete=\"+beanData[0].seq);\t\t\t// 데이터(리스트인데 배열처럼 받은걸 확인) 잘 받는지 모텔 이름 확인\r\n");
      out.write("        \t\r\n");
      out.write("        \tif(beanData.length!=0){\r\n");
      out.write("            \t$('#reservetable tr').slice(1).remove(); \t\t\t//원래 뿌렸던거 지움 \r\n");
      out.write("            \t//console.log(\"length=\"+beanData.length);\r\n");
      out.write("            \tfor(var i=0;i<beanData.length;i++){\r\n");
      out.write("            \t\tvar pay_dt = beanData[i].pay_dt;\r\n");
      out.write("            \t\tvar use_dt = beanData[i].use_dt;\r\n");
      out.write("            \t\tvar name = beanData[i].name;\r\n");
      out.write("            \t\tvar roomtype = beanData[i].room_type;\r\n");
      out.write("            \t\tvar price = beanData[i].price;\r\n");
      out.write("            \t\tvar state = beanData[i].state;\r\n");
      out.write("            \t\tvar totCnt = beanData[i].tot_cnt;\r\n");
      out.write("            \t\tvar seq = beanData[i].seq;\r\n");
      out.write("            \t\tvar point = beanData[i].point;\r\n");
      out.write("            \t\tvar choicevalue;\r\n");
      out.write("            \t\t//console.log(\"test=\"+beanData[i].name);\t// 데이터 잘 받는지 모텔 이름 확인\r\n");
      out.write("            \t\t//console.log(\"test=\"+beanData[i].state);\r\n");
      out.write("            \t\tif(state==0){\r\n");
      out.write("            \t\t\tstate=\"대기\";\r\n");
      out.write("            \t\t\tchoicevalue=\"0\"\r\n");
      out.write("            \t\t}else if(state==1){\r\n");
      out.write("            \t\t\tstate=\"확인\";\r\n");
      out.write("            \t\t\tchoicevalue=\"1\"\r\n");
      out.write("            \t\t}else if(state==2){\r\n");
      out.write("            \t\t\tstate=\"취소\";\r\n");
      out.write("            \t\t\tchoicevalue=\"2\"\r\n");
      out.write("            \t\t} \r\n");
      out.write("            \t\t\r\n");
      out.write("            \t\t$('#reservetable').append('<tr height=\"30\"><td style=\"border-bottom: 1px solid black;\">'+pay_dt+'</td><td style=\"border-bottom: 1px solid black;\">'+use_dt+'</td><td style=\"border-bottom: 1px solid black;\">'+name+'</td><td style=\"border-bottom: 1px solid black;\">'+roomtype+'</td><td style=\"border-bottom: 1px solid black;\">'+price+'</td><td style=\"border-bottom: 1px solid black;\"><button type=\"button\" id=\"reservechoice\" onclick=\"choice('+ choicevalue +','+seq+','+point+',' +price+');\">'+state+'</button></td></tr>'); \r\n");
      out.write("            \t}\r\n");
      out.write("            \t$(\"#reservetable\").append('<tr height=\"20\"><td colspan=\"6\" ></td></tr>');\r\n");
      out.write("                       \t\r\n");
      out.write("            \t// 페이징 숫자 처리 부분 \r\n");
      out.write("            \tvar pageCount = 0; \r\n");
      out.write("            \t\r\n");
      out.write("            \tif(totCnt%5>0){\r\n");
      out.write("            \t\tpageCount=Math.floor(totCnt/5)+1;\r\n");
      out.write("            \t}else{\r\n");
      out.write("            \t\tpageCount=Math.floor(totCnt/5);\r\n");
      out.write("            \t}\r\n");
      out.write("            \t//alert(\"pageCount\"+pageCount);\r\n");
      out.write("            \t\r\n");
      out.write("\t\t\t\tvar str = \"\";\r\n");
      out.write("    \t\t\tfor(i=0;i<pageCount;i++){\r\n");
      out.write("    \t\t\t\tstr += \"<a href='javascript:;' onclick='page(\"+(i+1)+\")' >\"+(i+1)+\"</a> \";\t\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t\t//alert(\"str\"+str);\r\n");
      out.write("           \t\r\n");
      out.write("            \t$(\"#reservetable\").append('<tr height=\"20\"><td colspan=\"6\" >'+\r\n");
      out.write("            \t\t\t       str     \t\t\t\r\n");
      out.write("            \t\t\t+'</td></tr>');\r\n");
      out.write("        \t}else{\r\n");
      out.write("        \t\t$('#reservetable tr').slice(1).remove();\r\n");
      out.write("        \t\t$(\"#reservetable\").append('<tr height=\"20\"><td colspan=\"6\" >내역이없습니다.</td></tr>');\r\n");
      out.write("        \t\treturn;\r\n");
      out.write("        \t}\r\n");
      out.write("        },\r\n");
      out.write("        complete : function(data) {\r\n");
      out.write("           // 통신이 실패했어도 완료가 되었을 때 이 함수를 타게 된다.\r\n");
      out.write("        \tconsole.log(\"complete\"+data);\r\n");
      out.write("        },           \r\n");
      out.write("        error:function(){\r\n");
      out.write("        }\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    $('#date1').change(function(){\r\n");
      out.write("    \tvar date1 = $('#date1').val();\r\n");
      out.write("    \tvar date2 = $('#date2').val();\r\n");
      out.write("    \t//alert(date);\r\n");
      out.write("    \t\r\n");
      out.write("    \t$(\"#date2\").attr( 'min', date1 );\r\n");
      out.write("    \t//$(\"#date1\").attr( 'max', date2 );\r\n");
      out.write("    \t//var dd = \"min='\"+date+\"'\";\r\n");
      out.write("    \t//alert(dd);\r\n");
      out.write("\t}); \r\n");
      out.write("\t\r\n");
      out.write("    $('#searchbtn').click(function(){\r\n");
      out.write("    \tpage(1);\r\n");
      out.write("    });  \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\t$('#week').click(function(){\r\n");
      out.write("    \tvar now = new Date();\r\n");
      out.write("        var year= now.getFullYear();\r\n");
      out.write("        var mon = (now.getMonth()+1)>9 ? ''+(now.getMonth()+1) : '0'+(now.getMonth()+1);\r\n");
      out.write("        var day = now.getDate()>9 ? ''+now.getDate() : '0'+now.getDate();\r\n");
      out.write("                \r\n");
      out.write("        var chan_val = year + '-' + mon + '-' + day;\r\n");
      out.write("        $('#date2').val(chan_val);\r\n");
      out.write("        //alert($('#date2').val());\r\n");
      out.write("        ///////////////////////////날짜일주일빼기///////////////////\r\n");
      out.write("\t\tvar selectDate = $('#date2').val().split(\"-\");\r\n");
      out.write("\t\tvar changeDate = new Date();\r\n");
      out.write("\t\tchangeDate.setFullYear(selectDate[0], selectDate[1]-1, selectDate[2]-7);\r\n");
      out.write("\r\n");
      out.write("\t\tvar y = changeDate.getFullYear();\r\n");
      out.write("\t\tvar m = changeDate.getMonth() + 1;\r\n");
      out.write("\t\tvar d = changeDate.getDate();\r\n");
      out.write("\t\tif(m < 10) { m = \"0\" + m; }\r\n");
      out.write("\t\tif(d < 10) { d = \"0\" + d; }\r\n");
      out.write("\r\n");
      out.write("\t\tvar resultDate = y + \"-\" + m + \"-\" + d;\r\n");
      out.write("\t\t$(\"#date1\").val(resultDate);\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#month').click(function(){\r\n");
      out.write("    \tvar now = new Date();\r\n");
      out.write("        var year= now.getFullYear();\r\n");
      out.write("        var mon = (now.getMonth()+1)>9 ? ''+(now.getMonth()+1) : '0'+(now.getMonth()+1);\r\n");
      out.write("        var day = now.getDate()>9 ? ''+now.getDate() : '0'+now.getDate();\r\n");
      out.write("                \r\n");
      out.write("        var chan_val = year + '-' + mon + '-' + day;\r\n");
      out.write("        $('#date2').val(chan_val);\r\n");
      out.write("        //alert($('#date2').val());\r\n");
      out.write("        ///////////////////////////날짜한달빼기///////////////////\r\n");
      out.write("\t\tvar selectDate = $('#date2').val().split(\"-\");\r\n");
      out.write("\t\tvar changeDate = new Date();\r\n");
      out.write("\t\tchangeDate.setFullYear(selectDate[0], selectDate[1]-2, selectDate[2]);\r\n");
      out.write("\r\n");
      out.write("\t\tvar y = changeDate.getFullYear();\r\n");
      out.write("\t\tvar m = changeDate.getMonth() + 1;\r\n");
      out.write("\t\tvar d = changeDate.getDate();\r\n");
      out.write("\t\tif(m < 10) { m = \"0\" + m; }\r\n");
      out.write("\t\tif(d < 10) { d = \"0\" + d; }\r\n");
      out.write("\r\n");
      out.write("\t\tvar resultDate = y + \"-\" + m + \"-\" + d;\r\n");
      out.write("\t\t$(\"#date1\").val(resultDate);\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#3month').click(function(){\r\n");
      out.write("    \tvar now = new Date();\r\n");
      out.write("        var year= now.getFullYear();\r\n");
      out.write("        var mon = (now.getMonth()+1)>9 ? ''+(now.getMonth()+1) : '0'+(now.getMonth()+1);\r\n");
      out.write("        var day = now.getDate()>9 ? ''+now.getDate() : '0'+now.getDate();\r\n");
      out.write("                \r\n");
      out.write("        var chan_val = year + '-' + mon + '-' + day;\r\n");
      out.write("        $('#date2').val(chan_val);\r\n");
      out.write("        //alert($('#date2').val());\r\n");
      out.write("        ///////////////////////////날짜세달빼기///////////////////\r\n");
      out.write("\t\tvar selectDate = $('#date2').val().split(\"-\");\r\n");
      out.write("\t\tvar changeDate = new Date();\r\n");
      out.write("\t\tchangeDate.setFullYear(selectDate[0], selectDate[1]-4, selectDate[2]);\r\n");
      out.write("\r\n");
      out.write("\t\tvar y = changeDate.getFullYear();\r\n");
      out.write("\t\tvar m = changeDate.getMonth() + 1;\r\n");
      out.write("\t\tvar d = changeDate.getDate();\r\n");
      out.write("\t\tif(m < 10) { m = \"0\" + m; }\r\n");
      out.write("\t\tif(d < 10) { d = \"0\" + d; }\r\n");
      out.write("\r\n");
      out.write("\t\tvar resultDate = y + \"-\" + m + \"-\" + d;\r\n");
      out.write("\t\t$(\"#date1\").val(resultDate);\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<center>\r\n");
      out.write("<table >\r\n");
      out.write("<col width=\"200\"/><col width=\"150\"/><col width=\"350\"/>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td height=\"50\" style=\"text-align: center; \" ><h4><b>예약내역</b></h4></td>\r\n");
      out.write("\t\t<td height=\"50\" style=\"text-align: center; border-right-color: #f3f3f3;\">예약기간조회</td>\r\n");
      out.write("\t\t<td height=\"50\" style=\"text-align: center;\">\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t\t<button type=\"button\" name=\"week\" id=\"week\">1주일</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" name=\"month\" id=\"month\">1개월</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" name=\"3month\" id=\"3month\">3개월</button><br>\r\n");
      out.write("\t\t\t\t<input type=\"date\" name=\"date1\" id=\"date1\" value=\"");
      out.print(todaydate );
      out.write("\" max=\"");
      out.print(todaydate);
      out.write("\" />\r\n");
      out.write("\t\t\t\t~\r\n");
      out.write("\t\t\t\t<input type=\"date\" name=\"date2\" id=\"date2\" value=\"");
      out.print(todaydate );
      out.write("\" min=\"");
      out.print(todaydate);
      out.write("\" />\r\n");
      out.write("\t\t\t\t<button type=\"button\" name=\"searchbtn\" id=\"searchbtn\">조회</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</center>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"padding-top: 30px\">\r\n");
      out.write("<center>\r\n");
      out.write("<table bordercolor=\"#000000\" id=\"reservetable\">\r\n");
      out.write("<col width=\"100\"/><col width=\"100\"/><col width=\"200\"/>\r\n");
      out.write("<col width=\"100\"/><col width=\"100\"/><col width=\"100\"/>\r\n");
      out.write("\t<tr bgcolor=\"#808000\" height=\"30\" id=\"headertr\">\r\n");
      out.write("\t\t<th style=\"text-align: center;\"><b>예약일자</b></th>\r\n");
      out.write("\t\t<th style=\"text-align: center;\"><b>사용일자</b></th>\r\n");
      out.write("\t\t<th style=\"text-align: center;\"><b>예약자</b></th>\r\n");
      out.write("\t\t<th style=\"text-align: center;\"><b>방종류</b></th>\r\n");
      out.write("\t\t<th style=\"text-align: center;\"><b>총 결제금액</b></th>\r\n");
      out.write("\t\t<th style=\"text-align: center;\"><b>승인여부</b></th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write(" \t<tr height=\"30\">\r\n");
      out.write(" \t\t<td colspan=\"6\">날짜를 선택해주세요</td>\r\n");
      out.write(" \t</tr>\r\n");
      out.write(" \t\r\n");
      out.write("</table>\r\n");
      out.write("</center>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("<center>\r\n");
      out.write("<table style=\"width: 50%; margin: auto;\" id=\"pagingtable\">\r\n");
      out.write("\t<col width=\"100\"/><col width=\"100\"/><col width=\"200\"/>\r\n");
      out.write("\t<col width=\"100\"/><col width=\"100\"/><col width=\"100\"/>\r\n");
      out.write(" \t\r\n");
      out.write("\t\r\n");
      out.write("\t</table>\r\n");
      out.write("</center>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
