/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2017-02-21 02:44:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.search;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.Beans.Ya_ImgBean;
import java.util.List;
import com.Dao.MotelDao;

public final class detailPhoto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

// 

//
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.Dao.MotelDao");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.Beans.Ya_ImgBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


request.setCharacterEncoding("UTF-8");

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("     <style>\r\n");
      out.write("      \r\n");
      out.write("      a{\r\n");
      out.write("      text-decoration : none;\r\n");
      out.write("      color : black;\r\n");
      out.write("      }\r\n");
      out.write("         \r\n");
      out.write("      .prev, .next {\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0;\r\n");
      out.write("      top: 50%;\r\n");
      out.write("      width: auto;\r\n");
      out.write("      margin-top: -22px;\r\n");
      out.write("      padding: 16px;\r\n");
      out.write("      color: black;\r\n");
      out.write("      font-size: 20px;\r\n");
      out.write("      transition: 0.4s ease;\r\n");
      out.write("      border-radius: 0 3px 3px 0;\r\n");
      out.write("      }\r\n");
      out.write("      .next {\r\n");
      out.write("      right: 0;\r\n");
      out.write("      border-radius: 3px 0 0 3px;\r\n");
      out.write("      }\r\n");
      out.write("      .prev:hover,.next:hover {\r\n");
      out.write("      background-color: rgba(0,0,0,0.8);\r\n");
      out.write("      }\r\n");
      out.write("     \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
//

String motelNum = request.getParameter("motelNum");
String str = request.getParameter("str");
String type = request.getParameter("type");

int noCount =0;
int preCount = 0;

MotelDao dao = MotelDao.getInstance();

List<Ya_ImgBean> list =  dao.do_detail_photo(Integer.parseInt(request.getParameter("motelNum")));
   
    if(type.equals("123")){
       System.out.println("일반실 이프 부분입니다.444444444444");
         for(int i=0;i<list.size();i++){ 
               if(list.get(i).getImg_auth()==1){noCount++;}
               System.out.println("파일어스"+list.get(i).getImg_auth()+"파일이름"+list.get(i).getImg_name());
         }
         System.out.println("일반실 이프 포문 끝나고 부분입니다.55555555555555===" + noCount);
    
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("      // 일반실 사진 개수     \r\n");
      out.write("      var noCount ='타입'+'");
      out.print(noCount);
      out.write("'; \r\n");
      out.write("      alert(typeof(noCount));\r\n");
      out.write("      var img1 =\"\";\r\n");
      out.write("      var img2 =\"\";\r\n");
      out.write("      var img3 =\"\";\r\n");
      out.write("\r\n");
      out.write("      ");
 if(noCount==1){
      out.write("\r\n");
      out.write("          img1 = \"");
      out.print(list.get(0).getImg_name());
      out.write("\";\r\n");
      out.write("      ");
}
 if(noCount==2){
      out.write("\r\n");
      out.write("         \r\n");
      out.write("          img1 = \"");
      out.print(list.get(0).getImg_name());
      out.write("\";\r\n");
      out.write("          img2 = \"");
      out.print(list.get(1).getImg_name());
      out.write("\";\r\n");
      out.write("      ");
}
 if(noCount==3){
      out.write("\r\n");
      out.write("           img1 = \"");
      out.print(list.get(0).getImg_name());
      out.write("\";\r\n");
      out.write("           img2 = \"");
      out.print(list.get(1).getImg_name());
      out.write("\";\r\n");
      out.write("           img3 = \"");
      out.print(list.get(2).getImg_name());
      out.write("\";\r\n");
      out.write("           \r\n");
      out.write("      ");
}
      out.write("   // 일반실 사진 개수 부분 끝 \r\n");
      out.write("      \r\n");
      out.write("      alert(\"일반 이미지1\"+img1);\r\n");
      out.write("      alert(\"일반 이미지2\"+img2);\r\n");
      out.write("      alert(\"일반 이미지3\"+img3); \r\n");
      out.write("      \r\n");
      out.write("      $(\"#next\").click(function(){\r\n");
      out.write("    \t \r\n");
      out.write("    \t  if(noCount==='타입1'){\r\n");
      out.write("              alert(\"사진이 한장입니다.\");\r\n");
      out.write("          \r\n");
      out.write("           }else if(noCount==='타입2'){\r\n");
      out.write("              \r\n");
      out.write("              if($(\"#first\").attr('src')==img1){\r\n");
      out.write("                  $(\"#first\").attr('src',img2);\r\n");
      out.write("                  \r\n");
      out.write("                  alert(\"일반 이미지2\"+img2);\r\n");
      out.write("                 \r\n");
      out.write("               }else if($(\"#first\").attr('src')==img2){\r\n");
      out.write("                  $(\"#first\").attr('src',img1);\r\n");
      out.write("                  alert(\"일반 이미지1\"+img1);\r\n");
      out.write("                 \r\n");
      out.write("               }\r\n");
      out.write("           \r\n");
      out.write("           }else if(noCount==='타입3'){\r\n");
      out.write("              \r\n");
      out.write("              if($(\"#first\").attr('src')==img1){\r\n");
      out.write("                  $(\"#first\").attr('src',img2);\r\n");
      out.write("                \r\n");
      out.write("                  alert(\"일반 이미지2\"+img2);\r\n");
      out.write("                  \r\n");
      out.write("               }else if($(\"#first\").attr('src')==img2){\r\n");
      out.write("                  $(\"#first\").attr('src',img3);\r\n");
      out.write("                 \r\n");
      out.write("                  alert(\"일반 이미지2\"+img2);\r\n");
      out.write("                  \r\n");
      out.write("               }else if($(\"#first\").attr('src')==img3){\r\n");
      out.write("                  $(\"#first\").attr('src',img1);\r\n");
      out.write("                  alert(\"일반 이미지1\"+img1);\r\n");
      out.write("                  \r\n");
      out.write("               }\r\n");
      out.write("        \r\n");
      out.write("              }\r\n");
      out.write("    \t  \r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      $(\"#prev\").click(function(){\r\n");
      out.write("                   \r\n");
      out.write("          if(noCount==='타입1'){\r\n");
      out.write("             alert(\"사진이 한장입니다.\");\r\n");
      out.write("          \r\n");
      out.write("          }else if(noCount==='타입2'){\r\n");
      out.write("             \tif($(\"#first\").attr('src')==img1){\r\n");
      out.write("                 $(\"#first\").attr('src',img2);\r\n");
      out.write("                 alert(\"일반 이미지2\"+img2);\r\n");
      out.write("              \t}else if($(\"#first\").attr('src')==img2){\r\n");
      out.write("                 $(\"#first\").attr('src',img1);\r\n");
      out.write("                 alert(\"일반 이미지1\"+img1);\r\n");
      out.write("             \t}\r\n");
      out.write("          \r\n");
      out.write("          }else if(noCount==='타입3'){\r\n");
      out.write("             if($(\"#first\").attr('src')==img1){\r\n");
      out.write("                 $(\"#first\").attr('src',img3);\r\n");
      out.write("                 alert(\"일반 이미지3\"+img3);\r\n");
      out.write("              }else if($(\"#first\").attr('src')==img3){\r\n");
      out.write("                 $(\"#first\").attr('src',img2);\r\n");
      out.write("                 alert(\"일반 이미지2\"+img2);\r\n");
      out.write("              }else if($(\"#first\").attr('src')==img2){\r\n");
      out.write("                 $(\"#first\").attr('src',img1);\r\n");
      out.write("                 alert(\"일반 이미지1\"+img1);\r\n");
      out.write("              }\r\n");
      out.write("               \r\n");
      out.write("          } \r\n");
      out.write("          \r\n");
      out.write("         \r\n");
      out.write("          \r\n");
      out.write("         \r\n");
      out.write("        });\r\n");
      out.write("      \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <a class=\"prev\" id=\"prev\" >&#10094;</a>\r\n");
      out.write("         \r\n");
      out.write("         <img id =\"first\" src=\"");
      out.print(list.get(0).getImg_name() );
      out.write("\" width=\"90%\" height=\"700\" style=\"margin-top: 7%; margin-left: 6%\">\r\n");
      out.write("         \r\n");
      out.write("    <a class=\"next\" id=\"next\" >&#10095;</a>\r\n");
      out.write("    \r\n");
      out.write("    ");

    return;
    }// 일반실 if 카운트 
    
    if(type.equals("789")){
       System.out.println("특실 이프 부분입니다.666666666666666666======" + list.size());
         for(int i=0;i<list.size();i++){ 
            if(list.get(i).getImg_auth()==2){
            	System.out.println(list.get(i).getImg_name());
            	preCount++;}
            if(list.get(i).getImg_auth()==2){noCount=i; break; }
         }
         System.out.println("특실 이프 포문 끝나고 부분입니다.7777777777777=====" + noCount );
         System.out.println("특실 이프 포문 끝나고 부분입니다.8888888888888=====" + preCount );
    
    
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("    \t$(document).ready(function(){\r\n");
      out.write("  \r\n");
      out.write("    \t\tvar noCount=");
      out.print(noCount);
      out.write("; \r\n");
      out.write("    \t      alert(typeof(noCount));\r\n");
      out.write("    \t    var preCount='특실'+'");
      out.print(preCount);
      out.write("';\r\n");
      out.write("    \t      var img1=\"\";\r\n");
      out.write("    \t      var img2=\"\";\r\n");
      out.write("    \t      var img3=\"\";\r\n");
      out.write("    \r\n");
      out.write("      ");
 if(preCount==1){
      out.write("\r\n");
      out.write("        img1 = \"");
      out.print(list.get(noCount).getImg_name());
      out.write("\";\r\n");
      out.write("      ");
}
 if(preCount==2){
      out.write("\r\n");
      out.write("   \t\timg1 = \"");
      out.print(list.get(noCount).getImg_name());
      out.write("\";\r\n");
      out.write("        img2 = \"");
      out.print(list.get(noCount+1).getImg_name());
      out.write("\";\r\n");
      out.write("        \r\n");
      out.write("      ");
}
 if(preCount==3){
      out.write("\r\n");
      out.write("   \t\timg1 = \"");
      out.print(list.get(noCount).getImg_name());
      out.write("\";\r\n");
      out.write("        img2 = \"");
      out.print(list.get(noCount+1).getImg_name());
      out.write("\";\r\n");
      out.write("        img3 = \"");
      out.print(list.get(noCount+2).getImg_name());
      out.write("\";\r\n");
      out.write("      ");
}
      out.write("\r\n");
      out.write("     \r\n");
      out.write("      \r\n");
      out.write("        alert(\"특실 이미지1\"+img1);\r\n");
      out.write("        alert(\"특실 이미지2\"+img2);\r\n");
      out.write("        alert(\"특실 이미지3\"+img3);\r\n");
      out.write("  \r\n");
      out.write("        $(\"#next\").click(function(){\r\n");
      out.write("       \t \r\n");
      out.write("      \t  if(preCount==='특실1'){\r\n");
      out.write("                alert(\"사진이 한장입니다.\");\r\n");
      out.write("            \r\n");
      out.write("             }else if(preCount==='특실2'){\r\n");
      out.write("                \r\n");
      out.write("                if($(\"#first\").attr('src')==img1){\r\n");
      out.write("                    $(\"#first\").attr('src',img2);\r\n");
      out.write("                 }else if($(\"#first\").attr('src')==img2){\r\n");
      out.write("                    $(\"#first\").attr('src',img1);\r\n");
      out.write("                 }\r\n");
      out.write("             \r\n");
      out.write("             }else if(preCount==='특실3'){\r\n");
      out.write("                \r\n");
      out.write("                if($(\"#first\").attr('src')==img1){\r\n");
      out.write("                    $(\"#first\").attr('src',img2);\r\n");
      out.write("                 }else if($(\"#first\").attr('src')==img2){\r\n");
      out.write("                    $(\"#first\").attr('src',img3);\r\n");
      out.write("                 }else if($(\"#first\").attr('src')==img3){\r\n");
      out.write("                    $(\"#first\").attr('src',img1);\r\n");
      out.write("                 }\r\n");
      out.write("          \r\n");
      out.write("                }\r\n");
      out.write("      \t  \r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        $(\"#prev\").click(function(){\r\n");
      out.write("            \r\n");
      out.write("            if(preCount==='특실1'){\r\n");
      out.write("               alert(\"사진이 한장입니다.\");\r\n");
      out.write("            \r\n");
      out.write("            }else if(preCount==='특실2'){\r\n");
      out.write("               \tif($(\"#first\").attr('src')==img1){\r\n");
      out.write("                   $(\"#first\").attr('src',img2);\r\n");
      out.write("                   alert(\"일반 이미지2\"+img2);\r\n");
      out.write("                \t}else if($(\"#first\").attr('src')==img2){\r\n");
      out.write("                   $(\"#first\").attr('src',img1);\r\n");
      out.write("                   alert(\"일반 이미지1\"+img1);\r\n");
      out.write("               \t}\r\n");
      out.write("            \r\n");
      out.write("            }else if(preCount==='특실3'){\r\n");
      out.write("               if($(\"#first\").attr('src')==img1){\r\n");
      out.write("                   $(\"#first\").attr('src',img3);\r\n");
      out.write("                   alert(\"일반 이미지3\"+img3);\r\n");
      out.write("                }else if($(\"#first\").attr('src')==img3){\r\n");
      out.write("                   $(\"#first\").attr('src',img2);\r\n");
      out.write("                   alert(\"일반 이미지2\"+img2);\r\n");
      out.write("                }else if($(\"#first\").attr('src')==img2){\r\n");
      out.write("                   $(\"#first\").attr('src',img1);\r\n");
      out.write("                   alert(\"일반 이미지1\"+img1);\r\n");
      out.write("                }\r\n");
      out.write("                 \r\n");
      out.write("            } \r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("          });\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("});    \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write(" \t <a class=\"prev\" id=\"prev\" >&#10094;</a>\r\n");
      out.write("          <img id =\"first\" src=\"");
      out.print(list.get(noCount).getImg_name() );
      out.write("\" width=\"90%\" height=\"700\" style=\"margin-top: 7%; margin-left: 6%\">\r\n");
      out.write("     <a class=\"next\" id=\"next\" >&#10095;</a>  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    }



//
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
