/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2017-02-21 02:44:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.search;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.Beans.Ya_ReviewBean;
import java.util.List;

public final class searchDetailReview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


public String arrow(int depth){
	String rs = "<img src='../img/arrow.png' width='50px' height='50px'>";
	String nbsp = "&nbsp;&nbsp;&nbsp;&nbsp;"; // 한칸씩 떨어트리는 규격 
	String ts="";
	for(int i=0; i<depth; i++){
		ts += nbsp;
	}
			// 0이라는건 첫번째 글이라는것 // 0이 아니면 답글이니깐 사진을 넣어라 
	return depth == 0 ? "":ts + rs;
}

public String star(int score){
	String star = "";
		if(score<4 && score>=2){
			star = "<img src='../img/pointstar.png' width='30px' height='30px'>&nbsp;"
				 + "<img src='../img/empty.png' width='30px' height='30px'>&nbsp;"
				 + "<img src='../img/empty.png' width='30px' height='30px'>&nbsp;"
				 + "<img src='../img/empty.png' width='30px' height='30px'>&nbsp;"
				 + "<img src='../img/empty.png' width='30px' height='30px'>&nbsp;";
		}else if(score<6 && score>=4){
			star = "<img src='../img/pointstar.png' width='30px' height='30px'>&nbsp;"
					 + "<img src='../img/pointstar.png' width='30px' height='30px'>&nbsp;"
					 + "<img src='../img/empty.png' width='30px' height='30px'>&nbsp;"
					 + "<img src='../img/empty.png' width='30px' height='30px'>&nbsp;"
					 + "<img src='../img/empty.png' width='30px' height='30px'>&nbsp;";
		}else if(score<8&&score>=6){
			star = "<img src='../img/pointstar.png' width='30px' height='30px'>&nbsp;"
					 + "<img src='../img/pointstar.png' width='30px' height='30px'>&nbsp;"
					 + "<img src='../img/pointstar.png' width='30px' height='30px'>&nbsp;"
					 + "<img src='../img/empty.png' width='30px' height='30px'>&nbsp;"
					 + "<img src='../img/empty.png' width='30px' height='30px'>&nbsp;";
		}else if(score<10&&score>=8){
			star = "<img src='../img/pointstar.png' width='30px' height='30px'>&nbsp;"
					 + "<img src='../img/pointstar.png' width='30px' height='30px'>&nbsp;"
					 + "<img src='../img/pointstar.png' width='30px' height='30px'>&nbsp;"
					 + "<img src='../img/pointstar.png' width='30px' height='30px'>&nbsp;"
					 + "<img src='../img/empty.png' width='30px' height='30px'>&nbsp;";
		}else if(score>8&&score<=10){
			star = "<img src='../img/pointstar.png' width='30px' height='30px'>&nbsp;"
					 + "<img src='../img/pointstar.png' width='30px' height='30px'>&nbsp;"
					 + "<img src='../img/pointstar.png' width='30px' height='30px'>&nbsp;"
					 + "<img src='../img/pointstar.png' width='30px' height='30px'>&nbsp;"
					 + "<img src='../img/pointstar.png' width='30px' height='30px'>&nbsp;";
		}
	return star;
}


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.Beans.Ya_ReviewBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


request.setCharacterEncoding("UTF-8");

//
 List<Ya_ReviewBean> list = (List<Ya_ReviewBean>)request.getAttribute("list");
String motelName = request.getParameter("motelName");
 
//
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>리뷰</h1>\r\n");
      out.write("<hr>\r\n");
      out.write("<div style=\" width: 100%; float: left; text-align: left\">\r\n");
 
if(list!=null){
	
int cleanscore=0;
int facilityscore=0;
int servicescore=0;
for(int i=0;i<list.size();i++){ 
facilityscore += list.get(i).getFacility();
cleanscore += list.get(i).getClean();
servicescore += list.get(i).getService();
} 

      out.write("\r\n");
      out.write("평균 : ");
      out.print(star((facilityscore+cleanscore+servicescore)/(list.size()*3)) );
      out.write("&nbsp;&nbsp;&nbsp;\r\n");
      out.write("시설점수 : ");
      out.print(star(facilityscore/list.size()) );
      out.write("&nbsp;&nbsp;&nbsp;\r\n");
      out.write("청결점수 : ");
      out.print(star(cleanscore/list.size()) );
      out.write("&nbsp;&nbsp;&nbsp;\r\n");
      out.write("서비스점수 : ");
      out.print(star(servicescore/list.size()) );
      out.write("&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<hr><hr>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

for (int i=0; i<list.size(); i++){ 
if(list.get(i).getDepth()==0){ 
      out.write("<div style=\" width: 80%; float: left; text-align: left\">\r\n");
      out.write("시설점수 : ");
      out.print(star(list.get(i).getFacility()) );
      out.write("\r\n");
      out.write("청결점수 : ");
      out.print(star(list.get(i).getClean()) );
      out.write("\r\n");
      out.write("서비스점수 : ");
      out.print(star(list.get(i).getService()) );
      out.write("<br>\r\n");
      out.write("닉네임 : ");
      out.print(list.get(i).getNickname() );
      out.write("<br><br>\r\n");
      out.write("내용 : ");
      out.print(list.get(i).getContent() );
      out.write("<br>\r\n");
      out.write("날짜 : ");
      out.print(list.get(i).getUpload_dt() );
      out.write("<br>\r\n");
      out.write("<hr>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
}if(list.get(i).getDepth()>0){ 
      out.write("<div style=\"background-color:lightgray; float: left; width: 80%; margin: auto; text-align: left\">\r\n");
      out.print(arrow(list.get(i).getDepth()) );
      out.print(motelName );
      out.write("사장님의 답글 <br>\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;내용 : ");
      out.print(list.get(i).getContent() );
      out.write("<br>\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;날짜 : ");
      out.print(list.get(i).getUpload_dt() );
      out.write("<br>\r\n");
      out.write("</div>\r\n");
      out.write("<br><br>\r\n");

	}
}

      out.write("<table style=\"width: 50%; margin: auto;\">\r\n");
      out.write("\t\t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    \t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    \t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    <tr>\r\n");
      out.write("    \t<td colspan=\"9\" align=\"center\">\r\n");
      out.write("    \t\r\n");
      out.write("    \t");

    	String str = " ";
    	int pageCount = list.get(0).getTot_cnt()%4 > 0 ? (list.get(0).getTot_cnt()/4)+1 : (list.get(0).getTot_cnt()/4); 
    	for(int i=0; i<pageCount;i++){
    	
      out.write("<a href=\"javascript:;\" onclick= \"location.href='searchControll.jsp?command=detailAf&type=review&pageNum=");
      out.print(i+1 );
      out.write("&motel_num=");
      out.print(list.get(0).getMotel_num() );
      out.write("'\" >\r\n");
      out.write("    \t<font size=\"5\">\r\n");
      out.write("    \t");
      out.print(i+1 );
      out.print(str );
} 
      out.write("</font>\r\n");
      out.write("    \t</a>\r\n");
      out.write("    \t</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t");

	
	}else{ 
      out.write("<div style=\"width: 100%; height: 700px; text-align: center; margin-top: 400px;\">\r\n");
      out.write("\t<h1>리뷰가 없습니다.</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");

	}
	
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
