/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2017-02-21 03:48:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.search;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.Beans.Ya_MotelBean;
import java.util.ArrayList;

public final class searchPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

//
//
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.Beans.Ya_MotelBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


request.setCharacterEncoding("UTF-8");

//
int imgCount = 0;
int contentCount = 0;

int count= 0;


ArrayList<Ya_MotelBean> list = (ArrayList<Ya_MotelBean>)request.getAttribute("list");


//
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- prevent IE6 flickering -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    try {\r\n");
      out.write("        document.execCommand('BackgroundImageCache', false, true);\r\n");
      out.write("    } catch (e) {\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    $(document).ready(function()\r\n");
      out.write("    \t\t{\r\n");
      out.write("    \t\t    $('#selectbox').change(function(){\r\n");
      out.write("    \t\t    \t");

    		    	if(session.getAttribute("word")!=null){ 
    		    		String searchWord = (String)session.getAttribute("word");
    		    		if(searchWord.equals("서울")||searchWord.equals("경기")||searchWord.equals("부산")||searchWord.equals("대전")||searchWord.equals("대구")){
    		    	
      out.write("\r\n");
      out.write("        \t\t        location.href='searchControll.jsp?isaddress=ok&command=word&type='+$('#selectbox option:selected').val()+ '&searchWord=");
      out.print(searchWord );
      out.write("';\r\n");
      out.write("        \t\t    ");

        		    }else{
        		    
      out.write("\r\n");
      out.write("    \t\t        \tlocation.href='searchControll.jsp?isaddress=no&command=word&type='+$('#selectbox option:selected').val()\r\n");
      out.write("    \t\t        \t+'&searchWord=");
      out.print(searchWord );
      out.write("';\r\n");
      out.write("    \t\t        ");

    		    		}
    		    	}
    		        
      out.write("\r\n");
      out.write("    \t\t    });\r\n");
      out.write("    \t\t});\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("    \t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.header{\r\n");
      out.write("\t\tposition : fixed;\r\n");
      out.write("\t\theight : 100px;\r\n");
      out.write("\t\tbackground: #fc676e;\r\n");
      out.write("\t}\r\n");
      out.write("\t.foot{\r\n");
      out.write("\t\theight : 200px;\r\n");
      out.write("\t\tbackground: #3f3e3e;\r\n");
      out.write("\t}\r\n");
      out.write("\t.blank{\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t}\t.location{\r\n");
      out.write("\t\tpadding-top : 50px;\r\n");
      out.write("\t\theight: 300px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.popular{\r\n");
      out.write("\t\theight: 300px;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable,tr,td{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\t/* border: 1px solid black */\r\n");
      out.write("\t}\r\n");
      out.write("\timg:hover{\r\n");
      out.write("\t\topacity: 0.5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.tabl{\r\n");
      out.write("\t\twidth: 60%;\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.tabl01{\r\n");
      out.write("\t\twidth: 80%;\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Top -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../super/superTop.jsp", out, false);
      out.write("<!-- 빈곳   -->\t\r\n");
      out.write("\t<div class=\"blank\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    \t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    \t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td></td>\r\n");
      out.write("    \t\t<td colspan=\"7\">________</td>\r\n");
      out.write("    \t\t<td></td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- 검색내용 -->\t\r\n");
      out.write("<br>\r\n");
      out.write("\t<table class=\"tabl\" >\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t<td height=\"100px\" align=\"center\">\r\n");
      out.write("    \t\t");

    		if(session.getAttribute("word")!=null){ 
    		String searchWord = (String)session.getAttribute("word");
    		
      out.write("<font face=\"맑은 고딕\" size=\"15\">");
      out.print(searchWord );
      out.write(" 검색 </font>\r\n");
      out.write("    \t\t");

    		}
    		
      out.write("</td>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td height=\"30\" style=\"text-align: right\">\r\n");
      out.write("    \t\t<select style=\"width: 150px; height: 30px;\" name=\"choi\" id=\"selectbox\">\r\n");
      out.write("    \t\t\t<option value=\"BASIC\" >조건 정렬</option>\r\n");
      out.write("\t\t\t\t<option value=\"PAY\" >가격 순</option>\r\n");
      out.write("\t\t\t\t<option value=\"STAR\" >별점 높은 순</option>\r\n");
      out.write("\t\t\t\t<option value=\"REVIEW\" >후기 많은 순</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<hr>\t \r\n");
      out.write("\t<input type=\"hidden\" name=\"command\" value=\"detail\">\r\n");
      out.write("\t<table class=\"tabl01\" style=\"background-color: #f2f2f2;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

		if(list!=null){
		
		int listSize = list.size()%4 > 0 ? (list.size()/4)+1 : (list.size()/4);
		//System.out.println("리스트 사이즈 " + listSize);
		
		
		for(int i=0; i<listSize; i++){ 
			count++;
			//System.out.println("count"+count);
		
      out.write("<tr>\r\n");
      out.write("\t\t");

		
		for(int j=0; j<4; j++){ 
		
			
    			if(count==listSize && list.size()%4 != 0){ 
    				if( j < list.size()%4){
    					//System.out.println("imgCount"+imgCount);
    					//System.out.println(list.get(imgCount).getImgs().get(0).getImg_name());
    	
      out.write("<td height=\"230\" width=\"60\"></td>\r\n");
      out.write("        \t\t<td height=\"230\" width=\"380\">\r\n");
      out.write("        \t\t<a href=\"searchControll.jsp?command=detail&motel_num=");
      out.print(list.get(imgCount).getMotel_num() );
      out.write("\">\r\n");
      out.write("        \t\t<img onerror=\"this.src='../img/noImg.gif'\" src=\"");
      out.print(list.get(imgCount).getImgs().get(0).getImg_name() );
      out.write("\" width=\"350\" height=\"230\">\r\n");
      out.write("        \t\t</a>\r\n");
      out.write("        \t\t</td>\r\n");
      out.write("        \t\t<td height=\"230\" width=\"60\"></td> \r\n");
      out.write("        ");
			imgCount++;
    				}else{
        
      out.write("<td height=\"230\" width=\"60\"></td>\r\n");
      out.write("            \t\t<td height=\"230\" width=\"380\" >\r\n");
      out.write("            \t\t</td>\r\n");
      out.write("            \t\t<td height=\"230\" width=\"60\"></td> \r\n");
      out.write("        ");
		
    			}
    		}else{
    			//System.out.println("imgCount++"+imgCount);
    	
      out.write("<td height=\"230\" width=\"60\"></td>\r\n");
      out.write("        \t\t<td height=\"230\" width=\"380\" >\r\n");
      out.write("        \t\t<a href=\"searchControll.jsp?command=detail&motel_num=");
      out.print(list.get(imgCount).getMotel_num() );
      out.write("\">\r\n");
      out.write("        \t\t<img onerror=\"this.src='../img/noImg.gif'\" src=\"");
      out.print(list.get(imgCount).getImgs().get(0).getImg_name() );
      out.write("\" width=\"350\" height=\"230\">\r\n");
      out.write("        \t\t</a></td>\r\n");
      out.write("        \t\t<td height=\"230\" width=\"60\"></td> \t\t\t\r\n");
      out.write("    \t");
		
    			imgCount++;
    		}
    	} 
    	
      out.write("</tr>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t");

    	for(int k=0; k<4; k++){  
    		System.out.println("count K "+count);
    			if(count==listSize && list.size()%4 != 0){ 
    				
    				if( k < list.size()%4){
    					//System.out.println("contentCount"+contentCount);		
    	
      out.write("<td height=\"80\" width=\"60\"></td>\r\n");
      out.write("    \t\t\t\t<td height=\"80\" width=\"380\" >\r\n");
      out.write("    \t\t\t\t<p>모텔 이름 : ");
      out.print(list.get(contentCount).getName() );
      out.write("</p>\r\n");
      out.write("    \t\t\t\t<p>주소 : ");
      out.print(list.get(contentCount).getAddress() );
      out.write("</p>\r\n");
      out.write("    \t\t\t\t<p>일반실 가격 : ");
      out.print(list.get(contentCount).getNormal_pri() );
      out.write("</p>\r\n");
      out.write("    \t    \t\t");
	
    	    			int cnt = list.get(contentCount).getStarAVG();	
    	    			for(int p = 0; p < cnt; ++p){
    	    		
      out.write("<img alt=\"\" src=\"../img/pointstar.png\" width=\"15px\" height=\"15px\">\r\n");
      out.write("    \t    \t\t");

    	    			}
    					for(int p = cnt; p < 10; ++p){
    	    		
      out.write("<img alt=\"\" src=\"../img/empty.png\" width=\"15px\" height=\"15px\">\r\n");
      out.write("    \t    \t\t");

    					}
    	    		
      out.write("</td>\r\n");
      out.write("    \t\t\t<td height=\"80\" width=\"60\"></td>\t\r\n");
      out.write("        ");
		contentCount++;
    				}else{
        
      out.write("<td height=\"80\" width=\"60\"></td>\r\n");
      out.write("    \t\t\t<td height=\"80\" width=\"380\" >\r\n");
      out.write("    \t\t\t</td>\r\n");
      out.write("    \t\t\t<td height=\"80\" width=\"60\"></td>\r\n");
      out.write("        ");
		
    			}
    		}else{
    	
      out.write("<td height=\"80\" width=\"60\"></td>\r\n");
      out.write("    \t\t\t<td height=\"80\" width=\"380\" >\r\n");
      out.write("    \t\t\t<p>모텔 이름 : ");
      out.print(list.get(contentCount).getName() );
      out.write("</p>\r\n");
      out.write("    \t\t\t<p>주소 : ");
      out.print(list.get(contentCount).getAddress() );
      out.write("</p>\r\n");
      out.write("    \t\t\t<p>일반실 가격 : ");
      out.print(list.get(contentCount).getNormal_pri() );
      out.write("</p> \r\n");
      out.write("    \t\t\t");

    				int cnt = list.get(contentCount).getStarAVG();
    	    		for(int p = 0; p < cnt; ++p){
    	    	
      out.write("<img alt=\"\" src=\"../img/pointstar.png\" width=\"15px\" height=\"15px\">\r\n");
      out.write("    \t    \t\t");

    	    		}
    					for(int p = cnt-1; p < 10; ++p){
    	    		
      out.write("<img alt=\"\" src=\"../img/empty.png\" width=\"15px\" height=\"15px\">\r\n");
      out.write("    \t    \t\t");

    				}
    	    		
      out.write("</td>\r\n");
      out.write("    \t\t\t<td height=\"80\" width=\"60\"></td>\t\t\t\r\n");
      out.write("    \t");
	
    	//System.out.println("contentCount++"+contentCount);
    	contentCount++;
    		}
    	} 
    	
      out.write("</tr>\r\n");
      out.write("    \t\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td height=\"50\" colspan=\"9\"></td>\r\n");
      out.write("    \t\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t");

    	
		} 
    	
      out.write("</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<table style=\"width: 50%; margin: auto;\">\r\n");
      out.write("\t\t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    \t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    \t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    <tr>\r\n");
      out.write("    \t<td colspan=\"9\" align=\"center\">\r\n");
      out.write("    \t\r\n");
      out.write("    \t");

    	String str = " ";
    	int pageCount = list.get(0).getTOT_CNT()%12 > 0 ? (list.get(0).getTOT_CNT()/12)+1 : (list.get(0).getTOT_CNT()/12); 
    	for(int i=0; i<pageCount;i++){
    	

    	if(session.getAttribute("word")!=null || session.getAttribute("type")!=null){ 
    		String searchWord = (String)session.getAttribute("word");
    		String stype = (String)session.getAttribute("type");
    	
      out.write("<a href=\"javascript:;\" onclick= \"location.href='searchControll.jsp?command=word&isaddress=no&pageNum=");
      out.print(i+1 );
      out.write("&searchWord=");
      out.print(searchWord );
      out.write("&type=");
      out.print(stype );
      out.write("'\" >\r\n");
      out.write("    \t");
	
    	}else{
    	
      out.write("<a href=\"javascript:;\" onclick=\"location.href='searchControll.jsp?command=word&pageNum=");
      out.print(i+1 );
      out.write("&isaddress=no'\" >\r\n");
      out.write("    \t");

    	}
    	
      out.write("<font size=\"5\">\r\n");
      out.write("    \t");
      out.print(i+1 );
      out.print(str );
} 
    	
      out.write("</font>\r\n");
      out.write("    \t</a>\r\n");
      out.write("    \t</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t");
}
	else{
		
      out.write("<div style=\"width: 100%; height: 700px; text-align: center; margin-top: 400px;\">\r\n");
      out.write("\t<h1>검색 결과가 없습니다.</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");

	}
	
      out.write("<br>\r\n");
      out.write("\t\r\n");
      out.write("<!--Foot -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../super/superFoot.jsp", out, false);
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
