/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2017-02-21 01:30:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.File;
import java.util.Enumeration;
import com.Beans.Ya_ImgBean;
import com.Beans.Ya_MotelBean;
import com.oreilly.servlet.multipart.DefaultFileRenamePolicy;
import com.oreilly.servlet.MultipartRequest;
import com.Dao.ImgDao;
import com.Dao.MotelDao;
import com.Beans.Ya_MemberBean;
import com.Dao.MemberDao;

public final class ya_005floginControl_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.Beans.Ya_MotelBean");
    _jspx_imports_classes.add("com.Dao.MotelDao");
    _jspx_imports_classes.add("java.util.Enumeration");
    _jspx_imports_classes.add("com.oreilly.servlet.multipart.DefaultFileRenamePolicy");
    _jspx_imports_classes.add("com.Dao.ImgDao");
    _jspx_imports_classes.add("com.Beans.Ya_ImgBean");
    _jspx_imports_classes.add("com.Beans.Ya_MemberBean");
    _jspx_imports_classes.add("com.Dao.MemberDao");
    _jspx_imports_classes.add("java.io.File");
    _jspx_imports_classes.add("com.oreilly.servlet.MultipartRequest");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("utf-8");

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
	
		String command = request.getParameter("command");
		System.out.println(command);
		
				
		if(command.equals("login")){
			pageContext.forward("ya_login.jsp");
		}else if(command.equals("logout")){
			pageContext.forward("ya_loginAfter.jsp?type=logout");
		}else if(command.equals("motelupdate")){
			Ya_MemberBean memberBean = (Ya_MemberBean)session.getAttribute("member");
			String email = memberBean.getEmail();
			
			///////////////////////////////////////////////////이미지 업로드 초기세팅 
			request.setCharacterEncoding("utf-8");
			String realFolder = "";
			String uploadfile = "";
			int maxSize = 1024*1024*100;
			String encType = "utf-8";
			String contextRoot = application.getContextPath();
			System.out.println("contextRoot : " + contextRoot);
			String dir = application.getRealPath("/img");
			String savefile = dir;
			ServletContext scontext = getServletContext();
			
			MotelDao motelDao = MotelDao.getInstance();
			ImgDao imgDao = ImgDao.getInstance();

			Ya_MotelBean motelBean = new Ya_MotelBean();
			Ya_ImgBean imgBean = new Ya_ImgBean();
			//회원생성 --> 승인여부는 아직 0!
			String str ="";
			
			/////////////////////////////////////////////////////////////////////////////// 서버에 저장 하는 부분 
			try{ 
				MultipartRequest multi = new MultipartRequest(request, savefile, maxSize, encType, new DefaultFileRenamePolicy());
				
				uploadfile = multi.getFilesystemName("mainimg");
				
				System.out.println(uploadfile);
				File file = new File(savefile + uploadfile); // 파일생성 
				System.out.println("uploadfile : " + uploadfile + "savefile" + savefile);
				imgBean.setImg_name(contextRoot + "/img/" + uploadfile); // 파일저장하면서 이름 저장 
				int num = motelDao.getMotelNum(email);
				imgBean.setMotel_num(num);
				System.out.println("num : " + num );
				imgBean.setImg_auth(0);
				System.out.println("이미지이름 : " + imgBean.getImg_name());
				///////////////////////////////////////////////////////////////////////////////////////
				//String email = memberBean.getEmail();
				
				//모텔수정 
				String name = multi.getParameter("motel");
				System.out.println("모텔명 :" + name);
				
				String phone = multi.getParameter("phone");
				System.out.println("전화번호 :" + phone);
				
				String checkin = multi.getParameter("checkIn");
				System.out.println("checkin :" + checkin);
				
				String checkout = multi.getParameter("checkOut");
				System.out.println("checkOut :" +checkout);
				
				String normalPrice = multi.getParameter("normalPrice");
				System.out.println("normalPrice :" + normalPrice);
				
				String premiumPrice = multi.getParameter("premiumPrice");
				System.out.println("premiumPrice :" + premiumPrice);
				
				String normalCnt = multi.getParameter("normalCnt");
				System.out.println("normalCnt :" + normalCnt);
				
				String premiumCnt = multi.getParameter("premiumCnt");
				System.out.println("premiumCnt :" + premiumCnt);
				
				motelBean.setEmail(email);
				motelBean.setName(name);
				motelBean.setPhone(phone);
				motelBean.setNormal_cnt(Integer.parseInt(normalCnt));
				motelBean.setPremium_cnt(Integer.parseInt(premiumCnt));
				motelBean.setNormal_pri(Integer.parseInt(normalPrice));
				motelBean.setPremium_pri(Integer.parseInt(premiumPrice));
				motelBean.setCheck_in(checkin);
				motelBean.setCheck_out(checkout);
				
				//int num = motelDao.getMotelNum(email);				
				//imgBean.setMotel_num(0);
				/* imgBean.setMotel_num(num);
				System.out.println("num : " + num );
				imgBean.setImg_auth(0);
				System.out.println("이미지이름 : " + imgBean.getImg_name()); */

			}catch(Exception e){
				e.printStackTrace();
			}			
			//사진 박기
			
			if(motelDao.do_update(motelBean)){
				System.out.println("모텔수정성공");
				if(!(imgBean.getImg_name().equals("/SIST_GIT_YA01/img/null"))){
					if(imgDao.do_update(imgBean)){
						System.out.println("이미지 됐다잉");
						pageContext.forward("../main/ya_main.jsp");
					}else{
						System.out.println("이미지 업로드실패");
						pageContext.forward("../main/ya_main.jsp");
					}
				}else{
					pageContext.forward("../main/ya_main.jsp");
				}
			}else{
				System.out.println("걍 첨부터 좆됌");
				pageContext.forward("../main/ya_main.jsp");
			}
			
		
		}else if(command.equals("update")){
			String password = request.getParameter("password");
			String email = request.getParameter("email");
			
			MemberDao memberDao = MemberDao.getInstance();
			Ya_MemberBean memberBean = new Ya_MemberBean();
			memberBean.setEmail(email);
			memberBean.setPassword(password);
			if(memberDao.do_update(memberBean)){
	
      out.write("\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\talert(\"정상 수정 되었습니다!\");\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t");

				pageContext.forward("../mypage/mypage_Main.jsp");
			}else{
				System.out.println(email);
				System.out.println(password);
				System.out.println("실패~");
			}
		}else if(command.equals("guestjoin")){
			
			MemberDao memberDao = MemberDao.getInstance();
			
			String email = request.getParameter("email");
			String password = request.getParameter("password");
			String nickname = request.getParameter("nickname");
			System.out.println(email + "," + nickname + "," + password);
			//nickname = new String(nickname.getBytes("ISO-8859-1"), "utf-8"); 
			//System.out.println("nickname=" + nickname );

			System.out.println(email + "," + nickname + "," + password);
			
			Ya_MemberBean memberBean = new Ya_MemberBean(email, password, nickname, 0, 0, 1,
					-1);			
			
			if(memberDao.do_insert(memberBean)){
				System.out.println("성공");
	
      out.write("\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\talert(\"가입성공!\");\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t");

			pageContext.forward("../main/ya_main.jsp");
			}else{
				System.out.println("실패");
	
      out.write("\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\talert(\"가입실패!\");\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t");

			pageContext.forward("../main/ya_main.jsp");
			}
	/////////////////////////////////////////////////////////////////////////사장회원가입	
		}else if(command.equals("hostjoin")){		
			String premiumImgCnt = "";
			String normalImgCnt = "";
			String str ="";			
			// 사진 추가 부분 
			MemberDao memberDao = MemberDao.getInstance();
					MotelDao motelDao = MotelDao.getInstance();
					
					Ya_MemberBean memberBean = new Ya_MemberBean();
					Ya_MotelBean motelBean = new Ya_MotelBean();
			 	
				ImgDao imgDao = ImgDao.getInstance();
				
				// 메인 사진 추가 
				try{ 
					Ya_ImgBean imgBean = new Ya_ImgBean();
					String contextRoot = application.getContextPath();
					System.out.println("contextRoot : " + contextRoot);
					// 저장경로
					String dir = application.getRealPath("/img");
					String savefile = dir;
					
					String realFolder = "";
					String filename1 = "";
					String uploadfile = "";
					int maxSize = 1024*1024*100;
					String encType = "utf-8";
									
					ServletContext scontext = getServletContext();
					
					
					MultipartRequest multi = new MultipartRequest(request, savefile, maxSize, encType, new DefaultFileRenamePolicy());
					
					premiumImgCnt = multi.getParameter("premiumImgCnt");
					normalImgCnt = multi.getParameter("normalImgCnt");
					
				///////회원정보와, 모텔정보 받아서 dto에 저장 
					String email = multi.getParameter("email");
					String password = multi.getParameter("password");
					String nickname = multi.getParameter("nickname");
					System.out.println(email + "," + nickname + "," + password);
					
					
					//회원생성 --> 승인여부는 아직 0!
					
									
					str = email;
					memberBean.setEmail(email);
					memberBean.setPassword(password);
					memberBean.setNickname(nickname);
					memberBean.setAuth(1);
					memberBean.setPoint(0);
					memberBean.setIs_ok(0);
					
					//모텔생성 --> 승인여부는 아직 0!
					String name = multi.getParameter("motel");
					String address = multi.getParameter("address");
					String phone = multi.getParameter("phone");
					String checkin = multi.getParameter("checkIn");
					String checkout = multi.getParameter("checkOut");
					String normalPrice = multi.getParameter("normalPrice");
					String premiumPrice = multi.getParameter("premiumPrice");
					String normalCnt = multi.getParameter("normalCnt");
					String premiumCnt = multi.getParameter("premiumCnt");
					
					motelBean.setMotel_num(0);
					motelBean.setEmail(email);
					motelBean.setName(name);
					motelBean.setAddress(address);
					motelBean.setPhone(phone);
					motelBean.setNormal_cnt(Integer.parseInt(normalCnt));
					motelBean.setPremium_cnt(Integer.parseInt(premiumCnt));
					motelBean.setNormal_pri(Integer.parseInt(normalPrice));
					motelBean.setPremium_pri(Integer.parseInt(premiumPrice));
					motelBean.setIs_ok(0);
					motelBean.setCheck_in(checkin);
					motelBean.setCheck_out(checkout);
				
				///////////////////////////////////////////////////////////////////////////////////////////			
				
				
				 if(memberDao.do_insert(memberBean)){
						System.out.println("맴버추가성공");
						if(motelDao.do_insert(motelBean)){
							System.out.println("모텔추가성공");
									
		
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\talert(\"가입성공!\");\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t");

						
						}else{
						System.out.println("실패");
		
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\talert(\"가입실패!\");\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t");

						pageContext.forward("../main/ya_main.jsp");
						return;
					}
				}else{
					System.out.println("실패");
		
      out.write("\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\talert(\"가입실패!\");\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t");

				pageContext.forward("../main/ya_main.jsp");
				return;
				}
				
					
					uploadfile = multi.getFilesystemName("mainimg");
					System.out.println("업로드파일"+uploadfile);
					File file = new File(savefile + uploadfile);
					System.out.println("uploadfile : " + uploadfile + "savefile" + savefile);
					
					
					
					int num = motelDao.getMotelNum(str);
					imgBean.setMotel_num(num);
					imgBean.setImg_name(contextRoot + "/img/" + uploadfile);
					imgBean.setImg_auth(0);
					
					imgDao.do_insert(imgBean);
					//////////////////////일반실 사진 
					for(int i=0;i<Integer.parseInt(normalImgCnt);i++){
						imgBean = new Ya_ImgBean();
						
						System.out.println("contextRoot : " + contextRoot);
						// 저장경로
												
						uploadfile = multi.getFilesystemName("noimg"+i);
						System.out.println("업로드파일"+uploadfile);
						file = new File(savefile + uploadfile);
						System.out.println("uploadfile : " + uploadfile + "savefile" + savefile);
						
						
						System.out.println("일반실사진 추가시 str" + str);
						num = motelDao.getMotelNum(str);
						imgBean.setMotel_num(num);
						imgBean.setImg_name(contextRoot + "/img/" + uploadfile);
						imgBean.setImg_auth(1);
						
						imgDao.do_insert(imgBean);
						
						
					}
					//////////////////////특실 사진 추가 
					if(Integer.parseInt(premiumImgCnt)>0){
					for(int i=0;i<Integer.parseInt(premiumImgCnt);i++){
						imgBean = new Ya_ImgBean();
						
						System.out.println("contextRoot : " + contextRoot);
						// 저장경로
												
						uploadfile = multi.getFilesystemName("preimg"+i);
						System.out.println("업로드파일"+uploadfile);
						file = new File(savefile + uploadfile);
						System.out.println("uploadfile : " + uploadfile + "savefile" + savefile);
						
						
						System.out.println("특실사진 추가시 str" + str);
						num = motelDao.getMotelNum(str);
						imgBean.setMotel_num(num);
						imgBean.setImg_name(contextRoot + "/img/" + uploadfile);
						imgBean.setImg_auth(2);
						
						imgDao.do_insert(imgBean);
						}
					
						pageContext.forward("../main/ya_main.jsp");
						return;
					}else{
						pageContext.forward("../main/ya_main.jsp");
						return;
					}
					
				}catch(Exception e){
					e.printStackTrace();
				}finally{
					
				}

						
			
				
		}
	
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
