/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2017-02-21 03:48:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.Beans.Ya_ImgBean;
import java.util.List;
import java.util.ArrayList;
import com.Beans.Ya_MotelBean;
import com.Dao.MainDao;

public final class ya_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.Beans.Ya_MotelBean");
    _jspx_imports_classes.add("com.Dao.MainDao");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.Beans.Ya_ImgBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://openapi.map.naver.com/openapi/v2/maps.js?clientId=xAmZfYgSTz_6UArTCRhz\"></script>\r\n");
      out.write("<!-- prevent IE6 flickering -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    try {\r\n");
      out.write("        document.execCommand('BackgroundImageCache', false, true);\r\n");
      out.write("    } catch (e) {\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<title>국내 no.1 모텔예약서비스</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.header{\r\n");
      out.write("\t\tposition : fixed;\r\n");
      out.write("\t\theight : 100px;\r\n");
      out.write("\t\tbackground: #fc676e;\r\n");
      out.write("\t\tz-index: 20;\r\n");
      out.write("\t}\r\n");
      out.write("\t.foot{\r\n");
      out.write("\t\theight : 200px;\r\n");
      out.write("\t\tbackground: #3f3e3e;\r\n");
      out.write("\t}\r\n");
      out.write("\t.blank{\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t.popular{\r\n");
      out.write("\t\theight: 450px; \r\n");
      out.write("\t\tmargin-bottom: 20px;\r\n");
      out.write("\t\tpadding-bottom: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable,tr,td{\r\n");
      out.write("\t\ttext-align: center;\t\r\n");
      out.write("\t\t/* border: 1px solid black; */\r\n");
      out.write("\t}\r\n");
      out.write("\timg:hover{\r\n");
      out.write("\t\t/* opacity: 0.5; */\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/*여기부터 시작  */\r\n");
      out.write("#carousel {\r\n");
      out.write("  margin-top : 250px;\r\n");
      out.write("  height: 350px;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  transform: translateY(-50%);\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("#carousel div {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  transition: transform 1s, left 1s, opacity 1s, z-index 0s;\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("#carousel div img {\r\n");
      out.write("  width: 400px;\r\n");
      out.write("  transition: width 1s;\r\n");
      out.write("}\r\n");
      out.write("#carousel div.hideLeft {\r\n");
      out.write("  left: 0%;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  transform: translateY(50%) translateX(-50%);\r\n");
      out.write("}\r\n");
      out.write("#carousel div.hideLeft img {\r\n");
      out.write("  width: 200px;\r\n");
      out.write("}\r\n");
      out.write("#carousel div.hideRight {\r\n");
      out.write("  left: 100%;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  transform: translateY(50%) translateX(-50%);\r\n");
      out.write("}\r\n");
      out.write("#carousel div.hideRight img {\r\n");
      out.write("  width: 200px;\r\n");
      out.write("}\r\n");
      out.write("#carousel div.prev {\r\n");
      out.write("  z-index: 5;\r\n");
      out.write("  left: 30%;\r\n");
      out.write("  transform: translateY(50px) translateX(-50%);\r\n");
      out.write("}\r\n");
      out.write("#carousel div.prev img {\r\n");
      out.write("  width: 300px;\r\n");
      out.write("}\r\n");
      out.write("#carousel div.prevLeftSecond {\r\n");
      out.write("  z-index: 4;\r\n");
      out.write("  left: 15%;\r\n");
      out.write("  transform: translateY(50%) translateX(-50%);\r\n");
      out.write("  opacity: 0.7;\r\n");
      out.write("}\r\n");
      out.write("#carousel div.prevLeftSecond img {\r\n");
      out.write("  width: 200px;\r\n");
      out.write("}\r\n");
      out.write("#carousel div.selected {\r\n");
      out.write("  z-index: 10;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  transform: translateY(0px) translateX(-50%);\r\n");
      out.write("}\r\n");
      out.write("#carousel div.next {\r\n");
      out.write("  z-index: 5;\r\n");
      out.write("  left: 70%;\r\n");
      out.write("  transform: translateY(50px) translateX(-50%);\r\n");
      out.write("}\r\n");
      out.write("#carousel div.next img {\r\n");
      out.write("  width: 300px;\r\n");
      out.write("}\r\n");
      out.write("#carousel div.nextRightSecond {\r\n");
      out.write("  z-index: 4;\r\n");
      out.write("  left: 85%;\r\n");
      out.write("  transform: translateY(50%) translateX(-50%);\r\n");
      out.write("  opacity: 0.7;\r\n");
      out.write("}\r\n");
      out.write("#carousel div.nextRightSecond img {\r\n");
      out.write("  width: 200px;\r\n");
      out.write("}\r\n");
      out.write(".buttons {\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  transform: translateX(-50%);\r\n");
      out.write("  bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#carousel{\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	MainDao mainDao = MainDao.getInstance();
	ArrayList<Object> list = mainDao.do_search(0,0,"","");

      out.write("\r\n");
      out.write("<!-- Top -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../super/superTop.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- 빈곳   -->\t\r\n");
      out.write("\t<div class=\"blank\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    \t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    \t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td></td>\r\n");
      out.write("    \t\t<td colspan=\"7\">________</td>\r\n");
      out.write("    \t\t<td></td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t \r\n");
      out.write("<!-- 지역별 업소 -->\r\n");
      out.write("\t<div id=\"carousel\">\r\n");
      out.write("\t<h3><span class=\"glyphicon glyphicon-search\"></span> 지역별 업소</h3><hr>\r\n");
      out.write("       <div class=\"hideLeft\">\r\n");
      out.write("       \t<a href=\"../search/searchControll.jsp?command=word&searchWord=부산&type=address\">\r\n");
      out.write("        <img src=\"../img/busan.jpg\" onmouseover = \"this.src = '../img/busanAf.png';\" onmouseout=\"this.src='../img/busan.jpg';\">\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"prevLeftSecond\">\r\n");
      out.write("      \t<a href=\"../search/searchControll.jsp?command=word&searchWord=경기&type=BASIC&isaddress=ok\">\r\n");
      out.write("        <img src=\"../img/kyungki.jpg\" onmouseover = \"this.src = '../img/kyungkiAf.png';\" onmouseout=\"this.src='../img/kyungki.jpg';\">\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"prev\">\r\n");
      out.write("      \t<a href=\"../search/searchControll.jsp?command=word&searchWord=인천&type=BASIC&isaddress=ok\">\r\n");
      out.write("        <img src=\"../img/incheon.jpg\" onmouseover = \"this.src = '../img/incheonAf.png';\" onmouseout=\"this.src='../img/incheon.jpg';\">\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"selected\">\r\n");
      out.write("      \t<a href=\"../search/searchControll.jsp?command=word&searchWord=서울&type=BASIC&isaddress=ok\">\r\n");
      out.write("        <img src=\"../img/map.png\">\r\n");
      out.write("        <p>내주변</p>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"next\">\r\n");
      out.write("      \t<a href=\"../search/searchControll.jsp?command=word&searchWord=서울&type=BASIC&isaddress=ok\">\r\n");
      out.write("        <img src=\"../img/seoul.jpg\" onmouseover = \"this.src = '../img/seoulAf.png';\" onmouseout=\"this.src='../img/seoul.jpg';\">\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"nextRightSecond\">\r\n");
      out.write("      \t<a href=\"../search/searchControll.jsp?command=word&searchWord=대구&type=BASIC&isaddress=ok\">\r\n");
      out.write("        <img src=\"../img/daegu.jpg\" onmouseover = \"this.src = '../img/daeguAf.png';\" onmouseout=\"this.src='../img/daegu.jpg';\">\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"hideRight\">\r\n");
      out.write("      \t<a href=\"../search/searchControll.jsp?command=word&searchWord=대전&type=BASIC&isaddress=ok\">\r\n");
      out.write("        <img src=\"../img/daejeon.jpg\" onmouseover = \"this.src = '../img/daejeonAf.png';\" onmouseout=\"this.src='../img/daejeon.jpg';\">\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"buttons\">\r\n");
      out.write("      <button id=\"prev\">Prev</button>\r\n");
      out.write("      <button id=\"next\">Next</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  function moveToSelected(element) {\r\n");
      out.write("\r\n");
      out.write("\t  if (element == \"next\") {\r\n");
      out.write("\t    var selected = $(\".selected\").next();\r\n");
      out.write("\t  } else if (element == \"prev\") {\r\n");
      out.write("\t    var selected = $(\".selected\").prev();\r\n");
      out.write("\t  } else {\r\n");
      out.write("\t    var selected = element;\r\n");
      out.write("\t  }\r\n");
      out.write("\r\n");
      out.write("\t  var next = $(selected).next();\r\n");
      out.write("\t  var prev = $(selected).prev();\r\n");
      out.write("\t  var prevSecond = $(prev).prev();\r\n");
      out.write("\t  var nextSecond = $(next).next();\r\n");
      out.write("\r\n");
      out.write("\t  $(selected).removeClass().addClass(\"selected\");\r\n");
      out.write("\r\n");
      out.write("\t  $(prev).removeClass().addClass(\"prev\");\r\n");
      out.write("\t  $(next).removeClass().addClass(\"next\");\r\n");
      out.write("\r\n");
      out.write("\t  $(nextSecond).removeClass().addClass(\"nextRightSecond\");\r\n");
      out.write("\t  $(prevSecond).removeClass().addClass(\"prevLeftSecond\");\r\n");
      out.write("\r\n");
      out.write("\t  $(nextSecond).nextAll().removeClass().addClass('hideRight');\r\n");
      out.write("\t  $(prevSecond).prevAll().removeClass().addClass('hideLeft');\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// Eventos teclado\r\n");
      out.write("\t$(document).keydown(function(e) {\r\n");
      out.write("\t    switch(e.which) {\r\n");
      out.write("\t        case 37: // left\r\n");
      out.write("\t        moveToSelected('prev');\r\n");
      out.write("\t        break;\r\n");
      out.write("\r\n");
      out.write("\t        case 39: // right\r\n");
      out.write("\t        moveToSelected('next');\r\n");
      out.write("\t        break;\r\n");
      out.write("\r\n");
      out.write("\t        default: return;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    e.preventDefault();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$('#carousel div').click(function() {\r\n");
      out.write("\t  moveToSelected($(this));\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$('#prev').click(function() {\r\n");
      out.write("\t  moveToSelected('prev');\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$('#next').click(function() {\r\n");
      out.write("\t  moveToSelected('next');\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t \r\n");
      out.write("<!-- 이달의 업소 -->\t\r\n");
      out.write("\t<div class=\"popular\" >\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    \t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    \t<col width=\"222\"/><col width=\"222\"/><col width=\"222\"/>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td colspan=\"9\"> </td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td colspan=\"9\"><h3><span class=\"glyphicon glyphicon-thumbs-up\"></span> 이달의 인기 업소</h3></td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td colspan=\"9\"><br><hr></td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td colspan=\"2\"></td>\r\n");
      out.write("    \t\t<td style=\"background-color: #fff7d8;\">1위</td>\r\n");
      out.write("    \t\t<td style=\"background-color: #fff7d8;\">2위</td>\r\n");
      out.write("    \t\t<td style=\"background-color: #fff7d8;\">3위</td>\r\n");
      out.write("    \t\t<td style=\"background-color: #fff7d8;\">4위</td>\r\n");
      out.write("    \t\t<td style=\"background-color: #fff7d8;\">5위</td>\r\n");
      out.write("    \t\t<td colspan=\"2\"></td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td></td>\r\n");
      out.write("    \t\t<td rowspan=\"2\"></td>\r\n");
      out.write("    \t\t");

    			for(int i = 0; i < list.size(); ++i){
    				Ya_MotelBean motelBean = (Ya_MotelBean)list.get(i);
    				List<Ya_ImgBean> imgs = motelBean.getImgs();
    				System.out.println(imgs.get(0).getImg_name());
    		
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    \t\t<td style=\"background-color: #fffbea; padding: 10px;\"><img onerror=\"this.src='../img/noImg.gif'\" src=\"");
      out.print((imgs.get(0)).getImg_name());
      out.write("\" width=\"180\" height=\"160\" onclick=\"location.href='../search/searchControll.jsp?command=detail&motel_num=");
      out.print(motelBean.getMotel_num());
      out.write("'\"></td>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t");

    			}
    		
      out.write("\r\n");
      out.write("    \t\t<td rowspan=\"2\"></td>\r\n");
      out.write(" \t\t\t<td></td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td colspan=\"9\"></td>\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t<tr>\r\n");
      out.write("    \t\t<td colspan=\"2\"></td>\r\n");
      out.write("    \t\t");

    			for(int i = 0; i < list.size(); ++i){
    				Ya_MotelBean motelBean = (Ya_MotelBean)list.get(i);
    		
      out.write("\r\n");
      out.write("    \t\t<td style=\"background-color: #fff7d8; padding: 10px;\">");
      out.print(motelBean.getName() );
      out.write("</td>\r\n");
      out.write("    \t\t");

    			}
    		
      out.write("\r\n");
      out.write("    \t</tr>\r\n");
      out.write("    \t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<div id=\"testMap\" style=\" border:1px solid #000; width:1000px; height:400px; margin:150px;\"></div>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("    var oPoint = new nhn.api.map.LatLng(37.5552462,126.935164);\r\n");
      out.write("    nhn.api.map.setDefaultPoint('LatLng');\r\n");
      out.write("    oMap = new nhn.api.map.Map('testMap', {\r\n");
      out.write("        point: oPoint,\r\n");
      out.write("        zoom: 14,\r\n");
      out.write("        enableWheelZoom: true,\r\n");
      out.write("        enableDragPan: true,\r\n");
      out.write("        enableDblClickZoom: false,\r\n");
      out.write("        mapMode: 0,\r\n");
      out.write("        activateTrafficMap: false,\r\n");
      out.write("        activateBicycleMap: false, \r\n");
      out.write("        minMaxLevel: [1, 14],\r\n");
      out.write("        size: new nhn.api.map.Size(1000, 400)\r\n");
      out.write("    });\r\n");
      out.write("\t</script>\r\n");
      out.write("<!--Foot -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../super/superFoot.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
