/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2017-02-16 01:13:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.super_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.Beans.Ya_ImgBean;
import java.util.List;
import java.util.ArrayList;
import com.Beans.Ya_MotelBean;
import com.Dao.MainDao;

public final class superFoot_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.Beans.Ya_MotelBean");
    _jspx_imports_classes.add("com.Dao.MainDao");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.Beans.Ya_ImgBean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	response.setHeader("Cache-Control","no-store");   
	response.setHeader("Pragma","no-cache");   
	response.setDateHeader("Expires",0);   
	if (request.getProtocol().equals("HTTP/1.1")) 
         response.setHeader("Cache-Control", "no-cache"); 

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://openapi.map.naver.com/openapi/v2/maps.js?clientId=xAmZfYgSTz_6UArTCRhz\"></script>\r\n");
      out.write("<!-- prevent IE6 flickering -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    try {\r\n");
      out.write("        document.execCommand('BackgroundImageCache', false, true);\r\n");
      out.write("    } catch (e) {\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<title>야하자입니다!!</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.foot{\r\n");
      out.write("\t\theight : 220px;\r\n");
      out.write("\t\tbackground: #3f3e3e;\r\n");
      out.write("\t}\r\n");
      out.write("\t.blank{\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable,tr,td{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\t/* border: 1px solid black */\t\r\n");
      out.write("\t}\r\n");
      out.write("\timg:hover{\r\n");
      out.write("\t\topacity: 0.5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/*여기부터 시작  */\r\n");
      out.write("#carousel {\r\n");
      out.write("  margin-top : 250px;\r\n");
      out.write("  height: 350px;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  transform: translateY(-50%);\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("#carousel div {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  transition: transform 1s, left 1s, opacity 1s, z-index 0s;\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("#carousel div img {\r\n");
      out.write("  width: 400px;\r\n");
      out.write("  transition: width 1s;\r\n");
      out.write("}\r\n");
      out.write("#carousel div.hideLeft {\r\n");
      out.write("  left: 0%;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  transform: translateY(50%) translateX(-50%);\r\n");
      out.write("}\r\n");
      out.write("#carousel div.hideLeft img {\r\n");
      out.write("  width: 200px;\r\n");
      out.write("}\r\n");
      out.write("#carousel div.hideRight {\r\n");
      out.write("  left: 100%;\r\n");
      out.write("  opacity: 0;\r\n");
      out.write("  transform: translateY(50%) translateX(-50%);\r\n");
      out.write("}\r\n");
      out.write("#carousel div.hideRight img {\r\n");
      out.write("  width: 200px;\r\n");
      out.write("}\r\n");
      out.write("#carousel div.prev {\r\n");
      out.write("  z-index: 5;\r\n");
      out.write("  left: 30%;\r\n");
      out.write("  transform: translateY(50px) translateX(-50%);\r\n");
      out.write("}\r\n");
      out.write("#carousel div.prev img {\r\n");
      out.write("  width: 300px;\r\n");
      out.write("}\r\n");
      out.write("#carousel div.prevLeftSecond {\r\n");
      out.write("  z-index: 4;\r\n");
      out.write("  left: 15%;\r\n");
      out.write("  transform: translateY(50%) translateX(-50%);\r\n");
      out.write("  opacity: 0.7;\r\n");
      out.write("}\r\n");
      out.write("#carousel div.prevLeftSecond img {\r\n");
      out.write("  width: 200px;\r\n");
      out.write("}\r\n");
      out.write("#carousel div.selected {\r\n");
      out.write("  z-index: 10;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  transform: translateY(0px) translateX(-50%);\r\n");
      out.write("}\r\n");
      out.write("#carousel div.next {\r\n");
      out.write("  z-index: 5;\r\n");
      out.write("  left: 70%;\r\n");
      out.write("  transform: translateY(50px) translateX(-50%);\r\n");
      out.write("}\r\n");
      out.write("#carousel div.next img {\r\n");
      out.write("  width: 300px;\r\n");
      out.write("}\r\n");
      out.write("#carousel div.nextRightSecond {\r\n");
      out.write("  z-index: 4;\r\n");
      out.write("  left: 85%;\r\n");
      out.write("  transform: translateY(50%) translateX(-50%);\r\n");
      out.write("  opacity: 0.7;\r\n");
      out.write("}\r\n");
      out.write("#carousel div.nextRightSecond img {\r\n");
      out.write("  width: 200px;\r\n");
      out.write("}\r\n");
      out.write(".buttons {\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  transform: translateX(-50%);\r\n");
      out.write("  bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#carousel{\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");

	String pageName = "";

      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Footer -->\t\r\n");
      out.write("\t<div class=\"foot\" style=\"padding-top: 10px\">\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<p style=\"color: #d9d9db\"> \r\n");
      out.write("\t\t서울특별시 마포구 백범로 18 미화빌딩 3층 F강의장<br>\r\n");
      out.write("\t\tdeveloped by<br> \r\n");
      out.write("\t\t조윤행. 김영재. 배한주. 황인배<br>\r\n");
      out.write("\t\t<a href=\"instagram.com/haengtion.24/\">instagram.com/haengtion.24/</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div style=\"padding-top: 10px\">\r\n");
      out.write("\t\t\t<img src=\"../img/team.png\" width=\"55px\" height=\"55px\">\r\n");
      out.write("\t\t\t<img src=\"../img/document.png\" width=\"55px\" height=\"55px\">\r\n");
      out.write("\t\t\t<img src=\"../img/process.png\" width=\"55px\" height=\"55px\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t <a href=\"../main/introduce.jsp\">팀소개 </a>\r\n");
      out.write("\t\t <a href=\"../main/useAppointment.jsp\">이용약관 </a>\r\n");
      out.write("\t\t <a href=\"http://blog.naver.com/dbsgod5880\">제작과정</a>\r\n");
      out.write("\t\t <p style=\"color: #d9d9db\">COPYRIGHT SIST_Fclass_2nd Project FirstTeam</p>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t\t </center>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
